### ISSUE TITLE
Emoji crashes scans

### ISSUE THREAD

**Issue by Tomaszu97** [P0cL4bs/wifipumpkin3#104]
I have a few network containing emojis, that seem to crash the script (wifi.wifiscan). Other tools have no issue with that. Not sure about other unicode characters.

**To Reproduce**
0.Have a network containing unicode symbols
1.Open wifipumpkin3
2.use wifi.wifiscan
3.set interface <interface_name>
4.run
5.observe - it should crash as soon as network with emoji is about to appear

**Expected behavior**
Scan should continue

**Screenshots** - well not a screenshot but heres an error:
`
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 0: ordinal not in range(128)
`

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). 1.0.7
* Virtual Machine (yes or no and which): no
* Operating System: ParrotOS
* version: 4.10

**Comment by nonnuocvietip** [comment]
Nel

**Comment by nonnuocvietip** [comment]
Passing

**Comment by MOOSEvac** [comment]
add this at wifiscan.py
 
import sys
import importlib
importlib.reload(sys)

#when >= Python 3.4

**Comment by Maximum123456789** [comment]
[-] the interface not found or is unavailable
