### ISSUE TITLE
please stop re-releasing version without version change. You break things

### ISSUE THREAD

**Issue by blshkv** [P0cL4bs/wifipumpkin3#106]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

**To Reproduce**
2. Run on '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
* Virtual Machine (yes or no and which): 
* Operating System:
* version: 

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by blshkv** [comment]
https://github.com/pentoo/pentoo-overlay/commit/6f9e25b14c313d2ccfb5e5ed719ece5de818dc27

**Comment by mh4x0f** [comment]
I had no choice about the last commit to fix a serious error that I had not tested before, look https://github.com/P0cL4bs/wifipumpkin3/commit/ec283e93b8606f2c82375a59f55efd92864634e3

**Comment by mh4x0f** [comment]
but in the next, I 'll add a v1.0.8R1

**Comment by blshkv** [comment]
btw, regarding suffix (R1) - this is not standard, it would be much easier if you could just increase the number, i.e. 1.0.9:
https://semver.org/
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
