### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#107]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

**To Reproduce**
1.  sudo wifipumpkin3 -i [interface]
**Expected behavior**
wifipumpkin3 should start without any errors

**Screenshots**

[*] starting pydhcp_server
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/packets/dnsserver.py", line 271, in run
    self.tcp_server = DNSServer(
  File "/usr/local/lib/python3.8/dist-packages/dnslib-0.9.14-py3.8.egg/dnslib/server.py", line 346, in __init__
    self.server = server((address,port),handler)
  File "/usr/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[+] starting captiveflask pid: [7310]

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `1.0.7 `).
* Virtual Machine (yes or no and which): yes
* Operating System: Ubuntu 
* version: 20.04.1 LTS

** INCOMPLETE REPORT WILL BE CLOSED *
What i have done:
1. i have done the necessary prep here: https://wifipumpkin3.github.io/docs/getting-started#based-on-debian-procedure
2. Look for open sockets 'lsof -i :80' (nothing shown)
3. Killed any python3 wifipumpkin3 that is still running.
4. Flush all iptables rules.
5. Cleared /root/.config/wifipumpkin3/config/hostapd/hostapd.conf

After doing all the above steps i still face the same issue.

**Comment by mh4x0f** [comment]
> Look for open sockets 'lsof -i :80' (nothing shown)

which port do I refer on the link https://wifipumpkin3.github.io/docs/getting-started#based-on-debian-procedure  ?

**Comment by junaidnaseer** [comment]
I face the exact same issue, except I am using Raspbian 10 (Debian 10 Buster). So obviously this is not a virtual machine.

I have performed all the fives steps that the OP jepunband had taken above.

>     i have done the necessary prep here: https://wifipumpkin3.github.io/docs/getting-started#based-on-debian-procedure
>     Look for open sockets 'lsof -i :80' (nothing shown)
>     Killed any python3 wifipumpkin3 that is still running.
>     Flush all iptables rules.
>     Cleared /root/.config/wifipumpkin3/config/hostapd/hostapd.conf
 

As I can see, neither port 53 nor port 80 are being used by any process.

And still I get the following message upon running pumpkinpi3.

I have tried this with different versions from v1.0.0 to v1.0.8R1. And all produce the same result.


> Starting prompt...
> wp3 > [+] hostapd is running
> [*] starting pydhcp_server
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.8-py3.7.egg/wifipumpkin3/core/packets/dnsserver.py", line 267, in run
>     self.resolver, port=port, logger=self.logger_dns, tcp=True
>   File "/usr/local/lib/python3.7/dist-packages/dnslib-0.9.14-py3.7.egg/dnslib/server.py", line 346, in __init__
>     self.server = server((address,port),handler)
>   File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
>     self.server_bind()
>   File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [Errno 98] Address already in use
> Aborted
> 

Should I open a new issue? Or maybe this issue would get reopened?
