### ISSUE TITLE
AP dosent start

### ISSUE THREAD

**Issue by thomastheheck** [P0cL4bs/wifipumpkin3#111]
Hey,

im trying to get my AP running for hours. I installed it on Kali Linux with python 3. I just dont know where the problem is. May you can help me.

![error](https://user-images.githubusercontent.com/75643053/101405672-bd99d980-38d8-11eb-8020-56a6028c16aa.png)

**Comment by Twink-Polar** [comment]
Looks like your trying to use 'eth0' as your interface to run hostapd on. You'll need to change that to a wireless interface e.g wlan1 or wlan0. 

Ethernet interfaces don't support access point mode, for hopefully obvious reasons. 

There is a guide on the wiki on how to do this.

**Comment by mh4x0f** [comment]
![](https://i.redd.it/dexgm72oq2u11.jpg)
