### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by mbnai** [P0cL4bs/wifipumpkin3#114]
Why it's not starting? I updated Python to 3.9 and other modules, but idk.![Screenshot 2020-12-11 213542.png](https://user-images.githubusercontent.com/63153011/101923294-6b6af800-3bf9-11eb-8f16-50dd88199028.png)

**Comment by deepmashru** [comment]
have you find any solutions??

**Comment by mbnai** [comment]
> have you find any solutions??
> 

Yeah, my bad. I had to just update repos.

**Comment by deepmashru** [comment]
tell how can i able to run this without this errors

**Comment by mbnai** [comment]
> tell how can i able to run this without this errors
> 

Simple
```
apt update && apt upgrade
```
helped me

**Comment by deepmashru** [comment]
i tried but it didn't work at all

**Comment by mbnai** [comment]
> i tried but it didn't work at all
> 

I don't know exactly. Then I'll reopen this issue. May be someone else know.
