### ISSUE TITLE
A startup error: 'SettingsINI' object has no attribute 'psettings'

### ISSUE THREAD

**Issue by chinggg** [P0cL4bs/wifipumpkin3#119]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

A python error throwed out at the very start so that wifi-pumpkin cannot work at all, which says `AttributeError: 'SettingsINI' object has no attribute 'psettings'`

**To Reproduce**
1. Add pacman source of `blackarch` to Manjaro
2. Run `sudo pacman -S wifi-pumpkin`
3. Run `wifi-pumpkin` either with or without root privilege, either with or without arguments
4. Always see the error
 
**Expected behavior**
Enter the interactive session or show some help information about correct usage.
**Screenshots**
```
Traceback (most recent call last):
  File "/usr/bin/wifi-pumpkin", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.0.8', 'console_scripts', 'wifipumpkin3')())
  File "/usr/lib/python3.9/site-packages/wifipumpkin3/__main__.py", line 79, in main
    config.set("accesspoint", "status_ap", False)
  File "/usr/lib/python3.9/site-packages/wifipumpkin3/core/utility/collection.py", line 47, in set
    self.psettings.beginGroup(name_group)
AttributeError: 'SettingsINI' object has no attribute 'psettings'
```
* Desktop (please complete the following information): Honor MagicBook with AMD Ryzen 5 3500U
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `): 2:v1.0.8R1.r0.g3b0b530-2 (pacman shows that since wifi-pumpkin cannot start at all)
* Virtual Machine (yes or no and which): no 
* Operating System: Manjaro with KDE
* version: Manjaro 20.2 Nibia, Kernel 5.10.2-2

Although I did not install `wifipumpkin3` by manually downloading the source code, I found the source code in `/usr/lib/python3.9/site-packages/` the same version. I have run `pip install -r requirements.txt` and most security tools installed by `pacman` work well. And I check the file `/usr/lib/python3.9/site-packages/wifipumpkin3/core/utility/collection.py`:
```
    def __init__(self, filename):
        if path.isfile(filename):
            self.psettings = QSettings(filename, QSettings.IniFormat)
```
It seems to have `psettings` in `SettingsINI`, I wonder why it throws this error.
Btw, #109 is the same error but that issuer leaves only one sentence of complaint. So I make this issue and try to provide enough information.

**Comment by mh4x0f** [comment]
hi, this error come from the configs files is not included on user directory (~/.config/wifipumpkin3), look doc:

https://wifipumpkin3.github.io/docs/configuration/configuration-file#configuration-structure

for solve this you can to add all files , i build a script for a user with same issue. the only think you do is run the script on directory of wifipumpkin3 installation or you can create the folders as can see on documentation. 

``` python
from distutils.util import strtobool
import os
import glob
import shutil
import re
from distutils.dir_util import copy_tree
import sys

folders = ["config", "logs", "helps", "scripts", "exceptions"]

def create_user_dir_config():
    user_config_dir = os.path.expanduser("~") + "/.config/wifipumpkin3"
    if not os.path.isdir(user_config_dir):
        os.makedirs(user_config_dir, exist_ok=True)
    # force copy all files `config` to user_config_dir
    for folder in folders:
        copy_tree(folder, user_config_dir + "/{}".format(folder))



create_user_dir_config()

```

**Comment by chinggg** [comment]
Thanks! The script you provide is quite helpful!
