### ISSUE TITLE
Failed to start captive portal

### ISSUE THREAD

**Issue by whoami00212** [P0cL4bs/wifipumpkin3#127]
So when i start captiveflask, set up proxies and also ap, i press start and access point appeard but when i connect to it the captive portal pop up does not appear. I use wlan0mon (in monitor mode for creating access point) and wlan1 for my normal wifi.

Expected behavior
New access point appear (Which is happening) then when i connect to it a new pop up appear for captive portal and when i clicked on that pop up it reditect user to fake captive portal. Then i get credentials.

Screenshots
https://prnt.sc/xmd4si
https://prnt.sc/xmd4z7
https://prnt.sc/xmd51y
https://prnt.sc/xmd55k

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). I'm using "wifipumpkin3 v1.0.8 branch: dev"
* Virtual Machine (yes or no and which): No i dont use vm 
* Operating System: Kali GNU/Linux Rolling x86_64
* version: Kernel: 5.9.0-kali5-amd64

![1](https://user-images.githubusercontent.com/77994812/105767422-a19dd600-5f20-11eb-8b63-f0ed026684ae.png)
![2](https://user-images.githubusercontent.com/77994812/105767439-a95d7a80-5f20-11eb-946c-91ebf2a1c23e.png)
![3](https://user-images.githubusercontent.com/77994812/105767447-ac586b00-5f20-11eb-862f-e356375368bd.png)
![4](https://user-images.githubusercontent.com/77994812/105767467-af535b80-5f20-11eb-842f-65508247ea8c.png)

**Comment by mh4x0f** [comment]
you will got this error because you follow the tutorial of `mcdonalds` template and changed the default code of captive flask binary. reinstall with defaults code should be solve the error.
