### ISSUE TITLE
After starting wifipumpkin3, the host and docker have no network

### ISSUE THREAD

**Issue by jinhay** [P0cL4bs/wifipumpkin3#128]
**Description of the bug or feature request**

After starting wifipumpkin3, the host and docker container have no network

**To Reproduce**
wp3 > set ssid 123
wp3 > set interface wlp61s0
wp3 > ignore
ignore
wp3 > ignore 
captiveflask   pumpkinproxy   pydhcp_server  pydns_server   responder3     sniffkin3      
wp3 > ignore pydhcp_server
wp3 > start

2、[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [180]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting pydns_server
[*] starting sniffkin3 port: [80, 8080]
 [  pydns_server  ] 06:10:54  - loading zone file "/root/.config/wifipumpkin3/config/app/dns_hosts.ini": 
[+] sniffkin3 -> emails     activated
[+] sniffkin3 -> httpCap    activated
[+] sniffkin3 -> kerberos   activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> ftp        activated
 [  pydns_server  ] 06:10:54  -   1: example.com.            300     IN      A       10.0.0.1 

 [  pydns_server  ] 06:10:54  -   2: example.com.            300     IN      CNAME   whatever.com. 
 [  pydns_server  ] 06:10:54  -   3: example.com.            300     IN      MX      5 whatever.com. 
 [  pydns_server  ] 06:10:54  -   4: example.com.            300     IN      MX      10 mx2.whatever.com. 
 [  pydns_server  ] 06:10:54  -   5: example.com.            300     IN      MX      20 mx3.whatever.com. 
 [  pydns_server  ] 06:10:54  -   6: example.com.            86400   IN      NS      ns1.whatever.com. 
 [  pydns_server  ] 06:10:54  -   7: example.com.            86400   IN      NS      ns2.whatever.com. 
 [  pydns_server  ] 06:10:54  -   8: example.com.            300     IN      TXT     "hello this is some text" 
 [  pydns_server  ] 06:10:54  -   9: example.com.            86400   IN      SOA     ns1.example.com. dns.example.com. 1611987048 3600 10800 86400 3600 
 [  pydns_server  ] 06:10:54  -  10: testing.com.            300     IN      TXT     "one long value: IICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgFWZUed1qcBziAsqZ/LzT2ASxJYuJ5sko1CzWFhFuxiluNnwKjSknSjanyYnm0vro4dhAtyiQ7OPVROOaNy9Iyklvu91KuhbYi6l80Rrdnuq1yjM//xjaB6DGx8+m1ENML8PEdSFbKQbh9akm2bkNw5DC5a8Slp7j+eEVHkgV3k3oRhkPcrKyoPVvniDNH+Ln7DnSGC" "+Aw5Sp+fhu5aZmoODhhX5/1mANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA26JaFWZUed1qcBziAsqZ/LzTF2ASxJYuJ5sk" 
 [  pydns_server  ] 06:10:54  - 10 zone resource records generated from zone file 

3、Before startup
 ping baidu.com
PING baidu.com (220.181.38.148) 56(84) bytes of data.
64 bytes from 220.181.38.148 (220.181.38.148): icmp_seq=1 ttl=52 time=37.8 ms
64 bytes from 220.181.38.148 (220.181.38.148): icmp_seq=2 ttl=52 time=37.1 ms
64 bytes from 220.181.38.148 (220.181.38.148): icmp_seq=3 ttl=52 time=37.9 ms

--- baidu.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 37.178/37.669/37.997/0.353 ms
 
4、After startup
ping baidu.com
ping: baidu.com: Unknown name or service

**Expected behavior**
I don't know what's wrong. I hope I can get help

**Screenshots**
**Desktop (please complete the following information):*wifipumpkin3 v1.0.8 branch: dev*
* Virtual Machine yes docker 
* Operating System: ubuntu 
* version:  Ubuntu 7.5.0-3ubuntu1~18.04

**Comment by jinhay** [comment]
My English is not good, please forgive me if you have any offence

**Comment by mh4x0f** [comment]
did you set the mode for docker ?

**Comment by jinhay** [comment]
Yes, I set it up. But still not

**Comment by jinhay** [comment]
> did you set the mode for docker ?

Yes, I set it up. But still not

**Comment by csim-20** [comment]
Untuk memblokir pengunga gimana
