### ISSUE TITLE
Issue related to cryptography while executing the wifipumpkin3 utility

### ISSUE THREAD

**Issue by bharathkarumudi** [P0cL4bs/wifipumpkin3#131]
**Description of the bug or feature request**
When running the Wifipumpkin3 on Kali, getting exception related to Cryptography and the process is getting exited. 

**To Reproduce**
run `sudo wifipumpkin3`
and getting the below exception and exited with exit code 1.
```
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 3.3.1 (/usr/lib/python3/dist-packages), Requirement.parse('cryptography<=3.2.1,>2.9.2'), {'jwt'})
```

**Expected behavior**
Generally when executed the utility, use to get the wifipumpkin3 console.

**Screenshots**
Added the stderr log file. 
[pumpkin-issue.txt](https://github.com/P0cL4bs/wifipumpkin3/files/5943326/pumpkin-issue.txt)

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `): unable to execute this, but installed from Git during Jan.
* Virtual Machine (yes or no and which): No
* Operating System: Kali
* version: 5.10.0-kali3-amd64 #1 SMP Debian 5.10.12-1kali1 (2021-02-03)

**Comment by mh4x0f** [comment]
hi, this has been fixed on commit [removed support to Rest API controller temporally](https://github.com/P0cL4bs/wifipumpkin3/commit/1d02e4a725a4cf32b5a2cc3130f3acfd62feedb3)
