### ISSUE TITLE
Graphic installation and another issue

### ISSUE THREAD

**Issue by SadLandscape** [P0cL4bs/wifipumpkin3#135]
Hello I just wanted to know is there a GUI interface for wp3 and when using CLI version I get and error saying hostapd is not running. It's dual boot kali linux 2021.1 secure boot is disabled (I don't know if this helps or not) installed from installation guide in docs (for kali linux)
Thanks in advance.

**Comment by csim-20** [comment]
> Hello I just wanted to know is there a GUI interface for wp3 and when using CLI version I get and error saying hostapd is not running. It's dual boot kali linux 2021.1 secure boot is enable (I don't know if this helps or not) installed from installation guide in docs (for kali linux)
> Thanks in advance.
