### ISSUE TITLE
wifipumpkin3 problem

### ISSUE THREAD

**Issue by cond8r** [P0cL4bs/wifipumpkin3#139]
I am using the deauth function of wifipumpkin3 but it always makes a mistake. I sent it out again, hope it can help me![image](https://user-images.githubusercontent.com/67705220/112272606-65d08400-8cb7-11eb-9386-e29298cef3c1.jpeg)![image](https://user-images.githubusercontent.com/67705220/112272607-65d08400-8cb7-11eb-8ce7-623626330971.jpeg)![image](https://user-images.githubusercontent.com/67705220/112272640-6cf79200-8cb7-11eb-93f9-a289210258fd.jpeg)

**Comment by cond8r** [comment]
My problem is still not solved, can you help me?

Marcos Bomfim ***@***.***> 于2021年7月27日周二 下午7:02写道：

**Comment by mh4x0f** [comment]
@cond8r  checkout the issue #104 , same problem but i can't fix it.

**Comment by cond8r** [comment]
Can you please tell me why you can't fix it because now I can't run it?
