### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alavalathi** [P0cL4bs/wifipumpkin3#14]
When trying to run the command wifipumpkin3 after sudo make install the application stops with the error message "IndexError: list index out of range"

* Wifipumpkin3 version  : wifipumpkin3 v1.0.0
* Virtual Machine           : No 
* Operating System       : Kali Linux 
* Version                        : 2020.2 / Kali-rolling

![error](https://user-images.githubusercontent.com/42601630/79687164-52997680-8213-11ea-891e-a56fe6ea18a6.png)

**Comment by mh4x0f** [comment]
@alavalathi thank's for report! hack the planet
