### ISSUE TITLE
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#140]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

**To Reproduce**
1. Go to wifipumpkin3 folder
2. Run sudo wifipumpkin3 -i wlan1
3. See error

**Expected behavior**
to be able for client to connect to AP and redirect to portal.

**Screenshots**
wp3 > start
[+] enable forwarding in iptables...
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

[*] sharing internet connection with NAT...
[*] settings for captive portal:
[*] allow FORWARD UDP DNS
[*] allow traffic to captive portal
[*] block all other traffic in access point
[*] redirecting HTTP traffic to captive portal
iptables v1.8.7 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument

iptables v1.8.7 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `1.0.8-dev `).
* Virtual Machine (yes or no and which): no
* Operating System: kali
* version: 2020.4

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by xpz3** [comment]
Uninstall iptables 1.8.7 and install iptables v1.6
There are other options to fix this too, but this would be the easiest. For a proper fix, wp3 needs to add support for nftables

**Comment by pohka174** [comment]
> Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.
> 
> **Description of the bug or feature request**
> 
> A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to wifipumpkin3 folder
> 2. Run sudo wifipumpkin3 -i wlan1
> 3. See error
> 
> **Expected behavior** to be able for client to connect to AP and redirect to portal.
> 
> **Screenshots** wp3 > start [+] enable forwarding in iptables... iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> 
> iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> 
> iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> 
> iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> 
> [_] sharing internet connection with NAT... [_] settings for captive portal: [_] allow FORWARD UDP DNS [_] allow traffic to captive portal [_] block all other traffic in access point [_] redirecting HTTP traffic to captive portal iptables v1.8.7 (nf_tables): unknown option "--dport" Try `iptables -h' or 'iptables --help' for more information. iptables v1.8.7 (nf_tables): unknown option "--dport" Try `iptables -h' or 'iptables --help' for more information. iptables v1.8.7 (nf_tables): Could not fetch rule set generation id: Invalid argument
> 
> iptables v1.8.7 (nf_tables): unknown option "--dport" Try `iptables -h' or 'iptables --help' for more information.
> 
> **Desktop (please complete the following information):**
> 
> * Wifipumpkin3 version you are using ( `1.0.8-dev `).
> * Virtual Machine (yes or no and which): no
> * Operating System: kali
> * version: 2020.4
> 
> ** INCOMPLETE REPORT WILL BE CLOSED *

2

I managed to get this to work with a workaround by replacing iptables with iptables-legacy (mainly to get ufw working)

You will need to do the following:

sudo touch /run/xtables.lock
sudo chmod a+r /run/xtables.lock
Easier to perform the next steps as root

sudo su - root
The following will move the iptables app that not working and copy the working legacy app

#!/bin/bash
mv /usr/sbin/iptables /usr/sbin/iptables-broken
cp /usr/sbin/iptables-legacy /usr/sbin/iptables
mv /usr/sbin/iptables-restore /usr/sbin/iptables-restore-broken
mv /usr/sbin/ip6tables-restore /usr/sbin/ip6tables-restore-broken
mv /usr/sbin/iptables-save /usr/sbin/iptables-save-broken
mv /usr/sbin/ip6tables-save /usr/sbin/ip6tables-save-broken
cp /usr/sbin/iptables-legacy-restore /usr/sbin/iptables-restore
cp /usr/sbin/ip6tables-legacy-restore /usr/sbin/ip6tables-restore
cp /usr/sbin/iptables-legacy-save /usr/sbin/iptables-save
cp /usr/sbin/ip6tables-legacy-save /usr/sbin/ip6tables-save

**Comment by pohka174** [comment]
2

I managed to get this to work with a workaround by replacing iptables with iptables-legacy (mainly to get ufw working)

You will need to do the following:

sudo touch /run/xtables.lock
sudo chmod a+r /run/xtables.lock
Easier to perform the next steps as root

sudo su - root
The following will move the iptables app that not working and copy the working legacy app

#!/bin/bash
mv /usr/sbin/iptables /usr/sbin/iptables-broken
cp /usr/sbin/iptables-legacy /usr/sbin/iptables
mv /usr/sbin/iptables-restore /usr/sbin/iptables-restore-broken
mv /usr/sbin/ip6tables-restore /usr/sbin/ip6tables-restore-broken
mv /usr/sbin/iptables-save /usr/sbin/iptables-save-broken
mv /usr/sbin/ip6tables-save /usr/sbin/ip6tables-save-broken
cp /usr/sbin/iptables-legacy-restore /usr/sbin/iptables-restore
cp /usr/sbin/ip6tables-legacy-restore /usr/sbin/ip6tables-restore
cp /usr/sbin/iptables-legacy-save /usr/sbin/iptables-save
cp /usr/sbin/ip6tables-legacy-save /usr/sbin/ip6tables-save

**Comment by stephenjamieson** [comment]
Try this instead:

`update-alternatives --set iptables /usr/sbin/iptables-legacy`

**Comment by morganzero** [comment]
> Sorry, but is not real issue that IP Tables have advanced and this solution has not? Why is back-reverting to older version of IP Tables considered a fix? Using iptables-legacy is just another flavor of a regression. Before everyone starts calling out that I am being critical, I am not, I am just asking why the real issue is not being addressed.

+1
