### ISSUE TITLE
handle_probe_req: Send failed

### ISSUE THREAD

**Issue by handleprobereq** [P0cL4bs/wifipumpkin3#141]
Hello, I am trying to host an AP with captive portal (Option 2 from your script) with:

alfa awus036nha atheros ar9271

And I am getting this error:
![handle_req](https://user-images.githubusercontent.com/81865509/113481008-83f86a00-9497-11eb-8f01-162f7dfc825c.png)

I tried to google it, but I can't find anything on it.
The AP works for a while then I get the error, when the error happens then I can't to connect to the AP anymore.

**Comment by xpz3** [comment]
Run `airmon-ng check kill` before running wp3

**Comment by handleprobereq** [comment]
> Run `airmon-ng check kill` before running wp3

It kills my network manager and then everything becomes unusable

**Comment by xpz3** [comment]
Set the interface to unmanaged

**Comment by IvanCR-ADIDAS** [comment]
hi, could you fix it?
