### ISSUE TITLE
misc.extra_captiveflask downloaded but not working.

### ISSUE THREAD

**Issue by jaykali** [P0cL4bs/wifipumpkin3#142]
misc.extra_captiveflask downloaded but not working.

**Expected behavior**
mise.extra_captiveflask is downloaded as you can see in the following screenshot. But when I try to install it is not working.

Tried reinstalling WP3 from Python3.7 and 3.4 but they are not working. currently this error comes when I use Python 3.9.1+

Please help me to figure this out.

**Screenshots**
[https://i.imgur.com/kEZdKjR.png](url)
**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
wifipumpkin3 v1.0.8 branch: dev
* Virtual Machine (yes or no and which): 
No
* Operating System: Kali Linux
* version: 2021.1

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
#151  check out this solution, probably is same error

**Comment by jaykali** [comment]
> #151 check out this solution, probably is same error

There is no solution. There I get a link of this issue, and here you posted a link of that issue. Round and round.. LOL
