### ISSUE TITLE
no internet available/connection

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#144]
Hello guys,

Does anyone here knows how to solve no internet connection on connected device to AP.  I'm using Kali and using latest wifipumpkin3 downloaded and setup today, 14/04/21.

Wifipumpkin3 starts without any errors. When device gets connected it shows no internet available and of course no redirect to portal.

**Comment by poison-ivy-3v3** [comment]
I'm having a similar issue, using Kali with the latest version of WP3.  Wifipumpkin3 starts the access point with no errors, I am able to have clients join the AP but with no internet access.  I have set the interface that the AP is using to Master mode prior to starting.  Is there a setting that needs to be changed to share a wireless internet connection in the proxies?  Any advice would be appreciated, thank  you!
