### ISSUE TITLE
Getting error while running custom login page

### ISSUE THREAD

**Issue by LRBx220** [P0cL4bs/wifipumpkin3#145]
After setting custom templates(custom login page) following the website tutorial it still gives error. but it works fine with other pages those are already available in wifipumpkin3. and also working with downloaded templates.
Note: After installing custom pages I run python3 setup.py install

**Screenshots**
![image](https://user-images.githubusercontent.com/83155927/115983541-9d3a9500-a5c3-11eb-90dc-992ee3359a08.png)

**Desktop (please complete the following information):**
*  wifipumpkin3 v1.0.8 branch: dev
* Virtual Box
* Operating System: Kali Linux Latest Version

**Comment by mh4x0f** [comment]
I can't help you, the documentation is very simple, you should be not following correctly the tutorial.

Please, 
follow the guides [how to create a plugins for captiveflask](https://wifipumpkin3.github.io/docs/getting-started#creating-captive-portal-template).
