### ISSUE TITLE
Crash after typing "list" [BUG]

### ISSUE THREAD

**Issue by tomektomula** [P0cL4bs/wifipumpkin3#153]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**
Trying to use "list" after "use misc.extra_captiveflask" causes wifipumpkin3 to crash

**To Reproduce**
sudo wifipumpkin3
use misc.extra_captiveflask
list
(crashes)

**Expected behavior**
shows list and allows to install plugin after download

**Screenshots**
https://i.imgur.com/7pxbhsP.png

**Desktop (please complete the following information):** laptop
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). wifipumpkin3 v1.0.8 branch: dev
* Virtual Machine (yes or no and which):  no
* Operating System: Ubuntu LTS
* version: Ubuntu 20.04.2 LTS 64bit

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
same error should be fix using the solution  #154
