### ISSUE TITLE
Cannot download "facebook" template for captiveflask [BUG]

### ISSUE THREAD

**Issue by tomektomula** [P0cL4bs/wifipumpkin3#154]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**
Cannot install the template

**To Reproduce**
sudo wifipumpkin3
use misc.extra_captiveflask
download
install facebook
(shows error: [-] directory wifipumpkin3/plugins/captiveflask not found )

**Expected behavior**
allows me to install the template

**Screenshots**
https://i.imgur.com/GkyqvQ5.png

**Desktop (please complete the following information):** laptop
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). wifipumpkin3 v1.0.8 branch: dev
* Virtual Machine (yes or no and which):  no
* Operating System: Ubuntu LTS
* version: Ubuntu 20.04.2 LTS 64bit

What I checked: 
In the directory from which I have installed wifipumpkin3, i went into a subdirectory also named "wifipumpkin3" and then to plugins. I could find captiveflask there.
https://i.imgur.com/9KpV1lP.png

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
@tomektomula  simple to solve this, for download the extra captive flask you need to be on wifipumpkin3 root directory.
