### ISSUE TITLE
have some error

### ISSUE THREAD

**Issue by littleheary** [P0cL4bs/wifipumpkin3#155]
wp3 > start
[+] enable forwarding in iptables...
SIOCSIFFLAGS: No such device
SIOCSIFFLAGS: No such device
SIOCSIFFLAGS: No such device
SIOCSIFFLAGS: No such device
SIOCADDRT: Network is down
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [1797]
wp3 > Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wifipumpkin3-1.0.8-py3.9.egg/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 151, in get_error_hostapdServices
    raise HostapdInitializeError(
wifipumpkin3.exceptions.errors.hostapdException.HostapdInitializeError: [ERROR] Hostpad Failed: check output process hostapd.
 Configuration file: /root/.config/wifipumpkin3/config/hostapd/hostapd.conf
Could not set interface wlan0 flags (UP): No such device
nl80211: Could not set interface 'wlan0' UP
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started
Aborted
root@kali:~/Desktop# ifconfig wlan0
wlan0: flags=4098<BROADCAST,MULTICAST>  mtu 1400
        inet 10.0.0.1  netmask 255.0.0.0  broadcast 10.255.255.255
        ether 6e:8c:4d:10:9b:18  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@kali:~/Desktop# iwconfig wlan0
wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by tomektomula** [comment]
bruh why didnt u use the template
