### ISSUE TITLE
client devices disconnected from the ap after a few minutes

### ISSUE THREAD

**Issue by GliderV5** [P0cL4bs/wifipumpkin3#158]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**
a few minutes after launching the access point, all connected devices are disconnected and cannot reconnect. Client devices get the following error message when trying to reconnect: Unable to authenticate connection. 

**To Reproduce**
1. sudo wifipumpkin3
2. set ssid test
3. set interface wlan0
4. set proxy noproxy
5. start

**Expected behavior**
that connected devices do not disconnect after a few minutes

**Desktop (please complete the following information): 
* Wifipumpkin3 version you are using : wifipumpkin3 v1.0.8 branch: dev
* Virtual Machine (yes or no and which): no
* Operating System: kali linux
* version: 2021.3

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by 4lch3my** [comment]
Same issue here on multiple Raspberry Pi's, running Kali and Ubuntu. In my case, I lose connection after a few seconds

**Comment by mh4x0f** [comment]
#156  this is the same problem. I 'm working on fix coming soon.

**Comment by mh4x0f** [comment]
I 'm working this on new version 1.0.9

**Comment by mh4x0f** [comment]
I released new version1.0.9 dev has support to dhcp (isc dhcp server) this feature allow use the robust implementation of dhcp and solve this problem.

**Comment by GliderV5** [comment]
> I released new version1.0.9 dev has support to dhcp (isc dhcp server) this feature allow use the robust implementation of dhcp and solve this problem.

thanks for the release, 
i just updated to version 1.0.9 dev, i selected ISC DHCPServer and when i run the access point, the client cannot connect to the access point (just the message "connecting ...") and i got the following message:
```
No subnet declaration for wlan0 (10.0.0.1).
** Ignoring requests on wlan0.  If this is not what
   you want, please write a subnet declaration
   in your dhcpd.conf file for the network segment
   to which interface wlan0 is attached. **


Not configured to listen on any interfaces!

If you think you have received this message due to a bug rather
than a configuration issue please read the section on submitting
bugs on either our web page at www.isc.org or in the README file
before submitting a bug.  These pages explain the proper
process and the information we find helpful for debugging.

exiting.

```

**Comment by mh4x0f** [comment]
@GliderV5 I try to reproduce this bug here and I confirmed. I working on fix, I 'll put here again. trhanks for feedback

**Comment by mh4x0f** [comment]
@GliderV5 I try to reproduce this bug here and I confirmed. I working on fix, I 'll put here again. trhanks for feedback

**Comment by GliderV5** [comment]
i just updated and the access point is working again in ISC mode. however the internet continues to cut out after about 5 minutes, and when I try to reconnect the device to the access point, it always tells me that it cannot authenticate the connection. To be able to reconnect I must restart the access point

**Comment by mh4x0f** [comment]
@GliderV5 I did everythink for solve this problem, if even running with ISC mode and  you got the same error, your card adapter not have full support with hostapd. because one contributor got this error running with especific card adapter that not working fine with hostapd. I think that will be great create a blackcard list here on docs for somes card thtat have support this feature. unfortunately, I can help you anymore for now. thanks for report.

**Comment by socialbiao** [comment]
also have same question

**Comment by mh4x0f** [comment]
@GliderV5 after almost 1 year i could reproduce this bug, this bug can be solve running the command `sudo airmon-ng check kill` before start the wp3. This command will be kill network-manager process that is block the card for using to create a AP, run this command solve the problem but i will add a implementation for ignore the card from network-manager like this this paper mecioned https://support.qacafe.com/knowledge-base/how-do-i-prevent-network-manager-from-controlling-an-interface/. btw, i m working on.

**Comment by mh4x0f** [comment]
Hi all, the solution for issue `client devices disconnected from the ap after a few minutes` is ignore the interface from network-manager. For settings this i add a option in command line to do this easily. checkout! 

![image](https://user-images.githubusercontent.com/6795613/202943031-7de85c2c-2bbc-4563-aaf9-3a4f053d34b9.png)
