### ISSUE TITLE
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by jezima** [P0cL4bs/wifipumpkin3#16]
when i run the command "sudo make install" it shows this error:

Installed /usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.0-py3.7.egg
Processing dependencies for wifipumpkin3==1.0.0
Searching for urwid==1.1.2
Reading https://pypi.python.org/simple/urwid/
Downloading https://files.pythonhosted.org/packages/a2/74/fa102f832959ef10ba3667609aa031e69298d8a1f45716bec245132a3039/urwid-1.1.2.tar.gz#sha256=f56568b4f8459b3265c65d9e275ef72df6cb16ad0c291f0feb027cc911ea0f26
Best match: urwid 1.1.2
Processing urwid-1.1.2.tar.gz
Writing /tmp/easy_install-fggesbp3/urwid-1.1.2/setup.cfg
Running urwid-1.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-fggesbp3/urwid-1.1.2/egg-dist-tmp-rvw0lxwe
warning: no files found matching 'CHANGELOG'
source/str_util.c:25:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
makefile:10: recipe for target 'install' failed
make: *** [install] Error 1
root@vozima:/home/vozima/wifipumpkin3# 

- i'm running Ubuntu 18.04.4 LTS on VirtualBox

i'm not running python3.7 default but i have installed it

<img width="960" alt="Screen Shot 2020-04-19 at 3 13 40 PM" src="https://user-images.githubusercontent.com/63386492/79701247-6c0ce380-8250-11ea-8cea-aed55b9b4d6d.png">

is there anything i'm missing? i've made sure i downloaded each of these to the latest version:

- iptables (current: iptables v1.6.1)
- iw (current: iw version 4.14)
- net-tools (current: version (1.60+)
- wireless-tools (current: version 30~pre9-12)
- hostapd (current: hostapd v2.6)

**Comment by jezima** [comment]
Pease Help (: ty

**Comment by mh4x0f** [comment]
I don't want to be rude, but before opening an issue put the error on google because it is a dependency error:
```
1. Open any browser 
2. type www.google.com
3. type "error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1" 
4. now, you can to see  66.600 results. 
```
follow this [link](https://github.com/scrapy/scrapy/issues/2115).

**Comment by jezima** [comment]
Ok thx my bad 🤪
