### ISSUE TITLE
it works when i switch to monitor mode,otherwise it's not working on managed mode

### ISSUE THREAD

**Issue by saadrehan77** [P0cL4bs/wifipumpkin3#168]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

**To Reproduce**
2. Run on '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
* Virtual Machine (yes or no and which): 
* Operating System:
* version: 

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
the wp3 not require any status mode for mount the AP because when the process to mount the AP is started the hostapd down the interface and disable.
