### ISSUE TITLE
Facebook captive portal not popping-up on device

### ISSUE THREAD

**Issue by Felipetsa** [P0cL4bs/wifipumpkin3#177]
Description of the bug or feature request

Once connected to the AP, an alert message displaying "This Wi-Fi has no Internet access" and captive portal does not pop-up.

To Reproduce

set interface wlan1
set ssid FreeWiFi
set proxy captiveflask
set captiveflask.facebook true
start

Expected behavior
The captive portal should appear as soon as the device connects to the AP "FreeWiFi"

Screenshots
https://i.postimg.cc/FzdcZK2N/Ek-VWROKj-IL.jpg
https://i.postimg.cc/NfXm256x/GFtnx-Dm-AUO.jpg
https://i.postimg.cc/SRB9thh8/p-Na-Qy-Lu-ARr.png
https://i.postimg.cc/qBS2783R/REFk-HHHwjo.png

Desktop (please complete the following information):

Wifipumpkin3 version you are using ( v1.1.2 dev ).
Virtual Machine (no):
Operating System: Kali
version: 2022.1
** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
Hi, @Felipetsa  maybe the problem is another services is not allow to share the internet connection. the solution is kill somes process using the airmon command, many user solve this problem using this.

so, after you reboot the OS and run that and try to mount the AP again.

``` console 
sudo airmon-ng check kill
```

**Comment by Felipetsa** [comment]
Hi @mh4x0f many thanks for your reply and sorry for my late reply! I will try it. Have a good week!
