### ISSUE TITLE
Traceback: PackageNotFoundError:

### ISSUE THREAD

**Issue by jeretc** [P0cL4bs/wifipumpkin3#183]
installation completes without errors ..

sudo python3 setup.py install
...
Using /usr/lib/python3/dist-packages
Finished processing dependencies for wifipumpkin3==1.1.2

**To Reproduce**
1. sudo wifipumpkin3

**Expected behavior**
wifipumpkin3 should launch

**Screenshots**
Traceback (most recent call last):
  File "/usr/bin/wifipumpkin3", line 33, in <module>
    sys.exit(load_entry_point('wifipumpkin3==1.1.2', 'console_scripts', 'wifipumpkin3')())
  File "/usr/bin/wifipumpkin3", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: wifipumpkin

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).
* Virtual Machine (yes or no and which): Yes
* Operating System: Parrot Sec
* version: VERSION="5.0 (LTS)

**Comment by mh4x0f** [comment]
try to remove and install again the tool, this problem I cant reproduce it
