### ISSUE TITLE
Captiveflask not working

### ISSUE THREAD

**Issue by danielsuperone** [P0cL4bs/wifipumpkin3#185]
**Description of the bug or feature request**

The program works with noproxy however when I enable captive flask, I get an error, please see imgur attacked for this

**To Reproduce**
1) Sudo wifipumpkin3
2)proxy set captiveflask
3)start

**Expected behavior**
For a captive flask login to appear on clients

**Screenshots**
![16512459751721690941137345655928](https://user-images.githubusercontent.com/74113321/165975662-33f8d454-5619-4d08-a448-91276962f85e.jpg)

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using: latest release
* Virtual Machine yes vm ware
* Operating System: kali
* version: latest

**Comment by skirt228** [comment]
Is your device that connects to the AP able to get internet?

**Comment by Gagnon85** [comment]
I am having this same issue

Wifipumpkin3 version you are using: wifipumpkin3 v1.1.2 branch: dev
Virtual Machine: VirtualBox
Operating System: Kali
version: 2022.1
Host: Mac OS

tried in both bridged connection and NAT

**Comment by mh4x0f** [comment]
Hi, the problem is asn1crypto try to update the version to current version with no conflict:
```
pip3 install asn1crypto>=1.5.1
```
OBS:  this can broken another tool that using the version bellow this 1.5.1.
