### ISSUE TITLE
keyerror: urlsCap

### ISSUE THREAD

**Issue by D4rXz3n0n** [P0cL4bs/wifipumpkin3#20]
keyerror when running captiveflask and posting user and password from android device, indeed data contains POSTCreds and does not reference any urlsCap.
![Capture d’écran de 2020-04-24 17-52-10](https://user-images.githubusercontent.com/63714594/80232141-b5946e80-8654-11ea-82a2-b66d5185051d.png)

**Comment by mh4x0f** [comment]
@D4rXz3n0n **I marked as invalid because you are not following the issue tamplate, any report is closed if you do not follow the issue template.**
about bug: this bug has solved on branch dev.

**Comment by D4rXz3n0n** [comment]
Got it ! Thanks for the precision, I will try to follow the issue template next time !
