### ISSUE TITLE
Hostapd error when starting AP

### ISSUE THREAD

**Issue by mcgregol** [P0cL4bs/wifipumpkin3#21]
Upon starting the AP, the program stops after successfully configuring the pydns server with the error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 127, in get_error_hostapdServices
    raise HostapdInitializeError(
wifipumpkin3.exceptions.errors.hostapdException.HostapdInitializeError: [ERROR] Hostpad Failed: check output process hostapd.
 Configuration file: /root/.config/wifipumpkin3/config/hostapd/hostapd.conf
Using interface wlan1mon with hwaddr bc:f6:85:03:36:5b and ssid "testing"
Failed to set beacon parameters
Interface initialization failed
wlan1mon: interface state UNINITIALIZED->DISABLED
wlan1mon: AP-DISABLED 
wlan1mon: Unable to setup interface.
wlan1mon: interface state DISABLED->DISABLED
wlan1mon: AP-DISABLED 
wlan1mon: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan1mon wasn't started
nl80211: deinit ifname=wlan1mon disabled_11b_rates=0
Aborted`

The parameters I set:

`set interface wlan1mon`
`set ssid testing`
`set proxy noproxy`

Using wifipumpkin3 v1.0.0 on live usb running Kali 2020.1b

**Comment by jezima** [comment]
did u download hostapd?

**Comment by mh4x0f** [comment]
@mcgregol why are you passing the interface in monitor mode? 
Read the doc it not necessary, hostapd not require mode monitor enable AP, checkout the documentation of [hostapd](https://wireless.wiki.kernel.org/en/users/documentation/hostapd)

**Comment by mcgregol** [comment]
@mh4x0f Ok, thanks, will try that

**Comment by mh4x0f** [comment]
I fix it unblocking the wifi adapter:
``` bash
sudo rfkill unblock wifi
```
You can check the blocking status with:
``` sh
rfkill list
```
font: https://github.com/ct-Open-Source/tuya-convert/issues/139
