### ISSUE TITLE
AP Can't not provide internet 

### ISSUE THREAD

**Issue by GA0LU** [P0cL4bs/wifipumpkin3#215]
**Description of the bug or feature request**

clean install Kali Linux on VM,  have NAT on Eth0  with Host wifi.  

Wlan0 = UBS wifi adapter （Asus - AC56 [Realtek 8812AU）

**To Reproduce**

**Expected behaviour**
**Wifi AP can connect everything looks fine, but on the mobile device， shows the AP provides no Internet.**

**Screenshots**

Starting prompt...
wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [99652]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting pydns_server port: 53
[*] starting sniffkin3 port: [80, 8080]
[+] sniffkin3 -> ftp        activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> kerberos   activated
[+] sniffkin3 -> emails     activated
[+] sniffkin3 -> httpCap    activated

 [  pydns_server  ] 00:17:40  - loading zone file "/root/.config/wifipumpkin3/config/app/dns_hosts.ini": 
 [  pydns_server  ] 00:17:40  -   1: example.com.            300     IN      A       10.0.0.1 
 [  pydns_server  ] 00:17:40  -   2: example.com.            300     IN      CNAME   whatever.com. 
 [  pydns_server  ] 00:17:40  -   3: example.com.            300     IN      MX      5 whatever.com. 
 [  pydns_server  ] 00:17:40  -   4: example.com.            300     IN      MX      10 mx2.whatever.com. 
 [  pydns_server  ] 00:17:40  -   5: example.com.            300     IN      MX      20 mx3.whatever.com. 
 [  pydns_server  ] 00:17:40  -   6: example.com.            86400   IN      NS      ns1.whatever.com. 
 [  pydns_server  ] 00:17:40  -   7: example.com.            86400   IN      NS      ns2.whatever.com. 
 [  pydns_server  ] 00:17:40  -   8: example.com.            300     IN      TXT     "hello this is some text" 
 [  pydns_server  ] 00:17:40  -   9: example.com.            86400   IN      SOA     ns1.example.com. dns.example.com. 1667103452 3600 10800 86400 3600 
 [  pydns_server  ] 00:17:40  -  10: testing.com.            300     IN      TXT     "one long value: IICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgFWZUed1qcBziAsqZ/LzT2ASxJYuJ5sko1CzWFhFuxiluNnwKjSknSjanyYnm0vro4dhAtyiQ7OPVROOaNy9Iyklvu91KuhbYi6l80Rrdnuq1yjM//xjaB6DGx8+m1ENML8PEdSFbKQbh9akm2bkNw5DC5a8Slp7j+eEVHkgV3k3oRhkPcrKyoPVvniDNH+Ln7DnSGC" "+Aw5Sp+fhu5aZmoODhhX5/1mANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA26JaFWZUed1qcBziAsqZ/LzTF2ASxJYuJ5sk" 
 [  pydns_server  ] 00:17:40  - 10 zone resource records generated from zone file 

**Desktop (please complete the following information):**  
* Wifipumpkin3 version you are using ( `[wifipumpkin3 --version](version: 1.1.4 main) `).
* Virtual Machine (yes VMware station PRO): 
* Operating System: Kali Linux

**Comment by mh4x0f** [comment]
look #195
