### ISSUE TITLE
All are working fine without issues except triggering captive portal (DarkLogin) from the client's machine

### ISSUE THREAD

**Issue by ethikhacker** [P0cL4bs/wifipumpkin3#216]
**Description of the bug or feature request**

I followed the proper installation process. All are working fine without issues, but captive portal(DarkLogin) does not load automatically in the client's browser when the client connect to the targeted AP. 

**Note:** When I manually entered http://10.0.0.1:80/ this url from the client's machine, It will load the captive portal login form as expected.

**To Reproduce**
1. sudo airmon-ng check kill
2. sudo wifipumpkin3
3. set interface wlan0
4. set ssid sampleHotspot
5. ignore pydns_server
6. set plugin sniffkin3 false
7. set proxy captiveflask
8. proxies
9. start

**Expected behavior**

Captive portal needs to load automatically when the client connect to the targeted AP. 

**Screenshots**
![image](https://user-images.githubusercontent.com/118042876/201467057-0c1e64fc-f515-45cd-b726-dc64121f7381.png)

![image](https://user-images.githubusercontent.com/118042876/201467216-0cbe1980-e662-4bc9-b9c7-dabe6c4a96be.png)

![Screenshot_20221112_143944_com android settings](https://user-images.githubusercontent.com/118042876/201467525-18fe0bfb-b136-40a9-810e-63d8686330d1.jpg)
![Screenshot_20221112_144004_com android settings](https://user-images.githubusercontent.com/118042876/201467526-498392e8-a4a6-46dc-b063-b88d93815e6d.jpg)

![image](https://user-images.githubusercontent.com/118042876/201467637-c3b04edf-e39c-480d-8186-251b46176139.png)

**Desktop:**
* Wifipumpkin3 version - wifipumpkin3 v1.1.4
* Virtual Machine (yes or no and which): - Yes (Oracle VM Virtualbox)
* Operating System: - kali linux
* version: - 2022.3
* kali-linux-2022.3-virtualbox-amd64

**Comment by mh4x0f** [comment]
check if you have internet connection on your machine, the wp3 is working fine.

**Comment by ethikhacker** [comment]
> check if you have internet connection on your machine, the wp3 is working fine.

When I connected to the AP. It shows no Internet access. Does it require additional Internet access?

**Comment by mh4x0f** [comment]
Captive portal require internet connection to work, you need to check if you have really internet in VM.

**Comment by ethikhacker** [comment]
> Captive portal require internet connection to work, you need to check if you have really internet in VM.

I do have internet connection in the VM also. It's not working

**Comment by ethikhacker** [comment]
https://user-images.githubusercontent.com/118042876/203122557-f5f83b1a-199e-44a4-ad84-2abc7fe14cc9.mp4

I have attached the screen recording for your reference.
