### ISSUE TITLE
Enhancment question, not issue

### ISSUE THREAD

**Issue by bytedeez** [P0cL4bs/wifipumpkin3#22]
Just wondering if you intended on making a GUI for the project like the original. I actually found the GUI faster and more accurate when doing mobile pentest with just a phone, a pi and a battery.

(I tried changing the label to reflect, not sure how to tho.)

**Comment by mh4x0f** [comment]
@bytedeez we intend to create a web UI when the API is functional.

**Comment by jezima** [comment]
how do you download the previous versions of wp?

**Comment by mh4x0f** [comment]
@jezima we haven't started development yet, we have other priorities at the moment. but everything new will be in the news branch
