### ISSUE TITLE
captiveflask internal server error 

### ISSUE THREAD

**Issue by Hzone-glitch** [P0cL4bs/wifipumpkin3#229]
**Expected behavior**
hi there
i downlod extra captive in " https://github.com/mh4x0f/extra-captiveflask " 
and i got error to test  with captiveflask (127.0.0.1:80).
and then i can not test my custom template.

(in the wp3 its work with 10.0.0.1:80) 
please help me thanks.

**Screenshots**
![Screenshot_2023-05-11_21_34_27](https://github.com/P0cL4bs/wifipumpkin3/assets/52880633/b9d93ead-cd02-411f-9d6c-1b43c479a3c9)
![Screenshot_2023-05-11_21_34_48](https://github.com/P0cL4bs/wifipumpkin3/assets/52880633/8d06db74-0663-48cf-92af-e3818224a8f9)
![Screenshot_2023-05-11_21_34_51](https://github.com/P0cL4bs/wifipumpkin3/assets/52880633/249f5e81-6c13-4442-9ddf-e869821c83f3)

* wifipumpkin3 v1.1.5 branch main 
* virtual machine: no
* Operating System  : Kali
* version: 2023

**Comment by mh4x0f** [comment]
Hi @Hzone-glitch this bug is because the exampleplugin is not exist anymore from the source. I find that the bast example that you can try is the facebook it more simple  to understand the code. checkout:
``` sh
sudo captiveflask -t $(pwd)/templates/facebook/ -r 127.0.0.1 -s $(pwd)/templates/facebook/static
```

**Comment by Hzone-glitch** [comment]
thank you 
its work!!
