### ISSUE TITLE
How to change the active captive flask template?

### ISSUE THREAD

**Issue by dwasyluk** [P0cL4bs/wifipumpkin3#231]
How do you change the active captiveflask / change it from DarkLogin to one of the others? The docs go through all the steps except for explaining how to change to new or different portals.

**Comment by mh4x0f** [comment]
look the doc: https://wifipumpkin3.github.io/docs/getting-started#proxies

**Comment by timyourivh** [comment]
You can set the template the same way you set config. 

```bash
set captiveflask.{template name} true
```

When setting a template to true, any other template will automatically be set to false.
 
For example, if I want to use the "Login_v4" template. I would type:

```bash
set captiveflask.Login_v4 true
```

You can confirm the changes by running the `proxies` command and checking the "Captive Portal plugins" section.

**Comment by timyourivh** [comment]
You can set the template the same way you set config. 

```bash
set captiveflask.{template name} true
```

When setting a template to true, any other template will automatically be set to false.
 
For example, if I want to use the "Login_v4" template. I would type:

```bash
set captiveflask.Login_v4 true
```

You can confirm the changes by running the `proxies` command and checking the "Captive Portal plugins" section.
