### ISSUE TITLE
Rust Installation error

### ISSUE THREAD

**Issue by h00p03** [P0cL4bs/wifipumpkin3#241]
**Description of the bug or feature request**

I installed rust version `1.56.0`. rust is installed correctly. I used `export PATH="$HOME/.cargo/bin:$PATH"` and `source ~/.bashrc`. After trying to install wifipumpkin3 I still have the error `This package requires Rust >=1.56.0.`

**To Reproduce**
1. `sudo python -m pip install --upgrade pip`
2. `sudo pip3 install setuptools-rust  `
3. `sudo python3 setup.py install `

**Expected behavior**
--

**Screenshots**
![image](https://github.com/P0cL4bs/wifipumpkin3/assets/76813955/0cec102e-c4dc-4141-9d55-108da4d728f5)

**Desktop (please complete the following information):**
* Wifipumpkin3: v1.1.5.
* Virtual Machine (yes or no and which):  no
* Operating System: Raspbian Lite
* version: 2023-05-03

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
https://wifipumpkin3.github.io/docs/getting-started
