### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('zope-interface>=5')

### ISSUE THREAD

**Issue by GaspardCulis** [P0cL4bs/wifipumpkin3#243]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

Error while installation with a python3.7 virtualenv:

```bash
error: Could not find suitable distribution for Requirement.parse('zope-interface>=5')
make: *** [makefile:20: install_env] Error 1
```

Saw it also happend in commit 5da92d6c329f9c63d44042163edac410cb027758 build step

**To Reproduce**

```bash
$ git clone https://github.com/P0cL4bs/wifipumpkin3.git
$ cd wifipumpkin3
$ sudo python3.7 -m pip install virtualenv

In root

# virtualenv -p python3.7 venv
# source venv/bin/activate
# make install_env
```

**Expected behavior**
Installation completed with this message:

`Finished processing dependencies for wifipumpkin3==1.0.0`

**Screenshots**

![image](https://github.com/P0cL4bs/wifipumpkin3/assets/79080828/cc97b426-fe70-42f3-91ae-db951d0d3632)

**Desktop (please complete the following information): 
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `). wifipumpkin3==1.1.5 commit ac4aa58a1060c783a1edb1f09920123442d0aa6b
* Virtual Machine (yes or no and which): No
* Operating System: Arch btw
* version: Kernel *6.4.12-zen1-1-zen*

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
this problem come from the cryptography library, try to remove ainda install again.

**Comment by mh4x0f** [comment]
try that:
```
sudo pip3 install zope.interface==6.1a2
```

**Comment by GaspardCulis** [comment]
Same error still after trying both installing before make, and after.
As I said this problem also happens on your side because the same error occurred in the latest commit [GH action buildstep](https://github.com/P0cL4bs/wifipumpkin3/actions/runs/5932711755/job/16086999962)

**Comment by mh4x0f** [comment]
I `m trying to find a solution for this bug because the problem come from the cryptography dependencies library. 

```
Installed /opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/cryptography-41.0.3-py3.8-linux-x86_64.egg
Searching for zope-interface>=5
```

**Comment by mh4x0f** [comment]
@GaspardCulis  the problem can be solve using the commnad:
```
sudo pip install .
```

using setup.py not is possible for now because the problem come from another package from python parser look that.

https://github.com/pypa/setuptools/pull/3153
https://github.com/dhatim/python-license-check/issues/81

but the solution updating for setuptools 62  not working for me. then, i 'll fix using the command above becasue the python setup.py install is deprecated so we have migrated to pyproject.toml.

**Comment by GaspardCulis** [comment]
Works like a charm without sudo in a virtualenv

**Comment by naiyerhaque** [comment]
heyy can i use wp3 in linux virtual machine ???
