### ISSUE TITLE
bug after starting ap

### ISSUE THREAD

**Issue by chydn0y** [P0cL4bs/wifipumpkin3#246]
1 wp3 > set interface wlan0mon
 2 
 3 wp3 > start
 4 
 5 [+] enable forwarding in iptables...
 6 
 7 SIOCSIFNETMASK: Cannot assign requested address
 8 
 9 SIOCADDRT: Network is unreachable
 10 
 11 [*] sharing internet connection with NAT...
 12 
 13 [*] setting interface for sharing internet: None 
 14 
 15 [+] starting hostpad pid: [8632]
 16 
 17 wp3 > Traceback (most recent call last):
 18 
 19   File "/usr/local/lib/python3.11/dist-packages/wifipumpkin3-1.1.5-py3.11.egg/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 159, in get_error_hostapdServices
 20 
 21     raise HostapdInitializeError(
 22 
 23 wifipumpkin3.exceptions.errors.hostapdException.HostapdInitializeError: [ERROR] Hostpad Failed: check output process hostapd.
 24 
 25  nl80211: deinit ifname=wlan0mon disabled_11b_rates=0
 26 
 27 nl80211 driver initialization failed.
 28 
 29 wlan0mon: interface state UNINITIALIZED->DISABLED

**Comment by mytricker0** [comment]
that is because you are in monitor mode. Go back to managed 
To be sure you have to check if you can connect to wifi

**Comment by mh4x0f** [comment]
that it, this error come from the monitor mode or the driver not it compatible with cardboard.
