### ISSUE TITLE
(self.get_mac_vendor) error after client joins 

### ISSUE THREAD

**Issue by WhimsicalWalrus** [P0cL4bs/wifipumpkin3#247]
Reinstalled everything so far, tried a different card, dhcp setup, keep getting the same. Unless I am looking at the solution and cant see it? Which I am more than happy to accept as I am "slow"

wifipumpkin3 --xpulp "set interface wlan0;set ssid TestP1-L1 ; set proxy noproxy; ignore pydns_server; set security true; set security.wpa_sharedkey 000000000; set security.wpa_algorithms CCMP; set bssid 00:00:00:00:00:00;start"

* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).  **version: 1.1.5 main**
* Virtual Machine (yes or no and which): **Vmware workstation pro 17**
* Operating System: **Kali** details in screenshot below
![1](https://github.com/P0cL4bs/wifipumpkin3/assets/103308133/f3e0470d-6332-474f-b12b-cedf2801edae)
![2](https://github.com/P0cL4bs/wifipumpkin3/assets/103308133/0eef6250-69a3-4159-9591-56267948f8e2)
![3](https://github.com/P0cL4bs/wifipumpkin3/assets/103308133/672bf752-effc-4238-939c-4d25d5e6f228)

**Comment by WhimsicalWalrus** [comment]
@mh4x0f - Can you please close this. Reinstalled Kali again - just installed drivers and wifipump and everything working. Suspect it was something else hogging dhcp (possibly), but everything is working at this stage. Cant go back to troubleshoot - clean install.

**Comment by mh4x0f** [comment]
I need to investigate this bug the error come from my code lol.

**Comment by WhimsicalWalrus** [comment]
> I need to investigate this bug the error come from my code lol.

Understood, let me know if I can help!

**Comment by mh4x0f** [comment]
This bug has been fixed on main branch https://github.com/P0cL4bs/wifipumpkin3/commit/ac4aa58a1060c783a1edb1f09920123442d0aa6b
