### ISSUE TITLE
AP doesnt share Internet connection

### ISSUE THREAD

**Issue by haraldschroder** [P0cL4bs/wifipumpkin3#248]
**Description of the bug or feature request**

When Starting wifipumpkin3, everything works as it should. Plugins, proxies and modes are working but in this case disabled, proxy=noproxy.
when starting AP
terminal says:[*] setting interface for sharing internet: eth0 
the AP works fine but no internet connection on host side.

└─$ sudo wifipumpkin3

                                            codename: Yorixiriamori
by: @mh4x0f - P0cL4bs Team | version: 1.1.5 main
[*] Session id: f7c5e0ac-6d8e-11ee-8b97-5c857e4a0c7b 
Starting prompt...
wp3 > set interface wlan0
wp3 > start
[+] enable forwarding in iptables...
[*] enable security authentication wireless
[*] sharing internet connection with NAT...
**[*] setting interface for sharing internet: eth0** 
[+] starting hostpad pid: [35170]
wp3 > [+] hostapd is running

Started Ap with connected device

wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[*] setting interface for sharing internet: eth0 
[+] starting hostpad pid: [39365]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting pydns_server port: 53
 [  pydns_server  ] 10:27:25  - loading zone file "/root/.config/wifipumpkin3/config/app/dns_hosts.ini": 
 [  pydns_server  ] 10:27:25  -   1: example.com.            300     IN      A       10.0.0.1 
 [  pydns_server  ] 10:27:25  -   2: example.com.            300     IN      CNAME   whatever.com. 
 [  pydns_server  ] 10:27:25  -   3: example.com.            300     IN      MX      5 whatever.com. 
 [  pydns_server  ] 10:27:25  -   4: example.com.            300     IN      MX      10 mx2.whatever.com. 
 [  pydns_server  ] 10:27:25  -   5: example.com.            300     IN      MX      20 mx3.whatever.com. 
 [  pydns_server  ] 10:27:25  -   6: example.com.            86400   IN      NS      ns1.whatever.com. 
 [  pydns_server  ] 10:27:25  -   7: example.com.            86400   IN      NS      ns2.whatever.com. 
 [  pydns_server  ] 10:27:25  -   8: example.com.            300     IN      TXT     "hello this is some text" 
 [  pydns_server  ] 10:27:25  -   9: example.com.            86400   IN      SOA     ns1.example.com. dns.example.com. 1697617130 3600 10800 86400 3600 
 [  pydns_server  ] 10:27:25  -  10: testing.com.            300     IN      TXT     "one long value: IICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgFWZUed1qcBziAsqZ/LzT2ASxJYuJ5sko1CzWFhFuxiluNnwKjSknSjanyYnm0vro4dhAtyiQ7OPVROOaNy9Iyklvu91KuhbYi6l80Rrdnuq1yjM//xjaB6DGx8+m1ENML8PEdSFbKQbh9akm2bkNw5DC5a8Slp7j+eEVHkgV3k3oRhkPcrKyoPVvniDNH+Ln7DnSGC" "+Aw5Sp+fhu5aZmoODhhX5/1mANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA26JaFWZUed1qcBziAsqZ/LzTF2ASxJYuJ5sk" 
 [  pydns_server  ] 10:27:25  - 10 zone resource records generated from zone file 
 [  pydhcp_server  ] 10:27:36  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('e0:e0:fc:22:40:fd')
        flags: 
        hops: 0
        secs: 0
        xid: 4118952040
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][012] hostname: 'XXXXXXXXXX'
        [-][053] dhcp_message_type: DHCP_DISCOVER
        [-][055] parameter_request_list: 053:dhcp_message_type
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'XXXXXXXXXXX'
        [ ][061] client_identifier: [480, 57596, 8768]
 
 [  pydhcp_server  ] 10:27:36  - DISCOVER: packet from 10.0.0.21 
 [  pydhcp_server  ] 10:27:36  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('XXXXXXXX')
        flags: 
        hops: 0
        secs: 0
        xid: 4118952040
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [ ][012] hostname: 'XXXXXXXXXXXXXXXXXXX'
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_OFFER
        [X][054] server_identifier: IPv4Address('10.0.0.1')
 
 [  pydhcp_server  ] 10:27:36  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('e0:e0:fc:22:40:fd')
        flags: 
        hops: 0
        secs: 0
        xid: 4118952040
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][012] hostname: 'XXXXXXXXXXX'
        [ ][050] requested_ip_address: IPv4Address('10.0.0.21')
        [-][053] dhcp_message_type: DHCP_REQUEST
        [X][054] server_identifier: IPv4Address('10.0.0.1')
        [-][055] parameter_request_list: 053:dhcp_message_type, 054:server_identifier
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][060] vendor_class_identifier: 'XXXXXXXXXX'
        [ ][061] client_identifier: [480, 57596, 8768]
 
 [  pydhcp_server  ] 10:27:36  - REQUEST: packet from 10.0.0.21 to 10.0.0.1 
[*] e0:e0:fc:22:40:fd client join the AP 
 [  pydhcp_server  ] 10:27:36  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('e0:e0:fc:22:40:fd')
        flags: 
        hops: 0
        secs: 0
        xid: 4118952040
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('10.0.0.21')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.0.0.0')
        [X][003] router: [IPv4Address('10.0.0.1'), IPv4Address('8.8.8.8')]
        [X][006] domain_name_servers: [IPv4Address('10.0.0.1')]
        [ ][012] hostname: 'XXXXXXXXXXXX'
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_ACK
        [X][054] server_identifier: IPv4Address('10.0.0.1')
 
 [  pydns_server  ] 10:27:37  - no local zone found, proxying connectivitycheck.platform.hicloud.com.[A] 
 [  pydns_server  ] 10:27:37  - no local zone found, proxying epdg.epc.mnc002.mcc262.pub.3gppnetwork.org.[A] 
 [  pydns_server  ] 10:27:37  - no local zone found, proxying mtalk.google.com.[A] 
 [  pydns_server  ] 10:27:38  - no local zone found, proxying hw.zuimeitianqi.com.[A] 
 [  pydns_server  ] 10:27:40  - no local zone found, proxying connectivitycheck.cbg-app.huawei.com.[A] 
ap

[*] Settings AccessPoint:
=========================

 bssid             | ssid           |   channel | interface   | interface_net   | status     | security   | hostapd_config
-------------------+----------------+-----------+-------------+-----------------+------------+------------+------------------
 BC:F6:85:03:36:5B | WiFi Pumpkin 3 |        11 | wlan0  | default         | is Running | false      | false

on host side no internet connection avaliable -> device won't connect automatically

**Expected behavior**
Internet connection on host side

* Wifipumpkin3 version: version: 1.1.5 main
* Virtual Machine (yes or no and which): no
* Operating System: Kali Purple
* version: PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

**Comment by mh4x0f** [comment]
try to change the ip range with command:
```
dhcpconf 1 
```
and start the ap after that, if this not work send for me the log: iptables with:
```
sudo iptables -t nat -L
```

**Comment by haraldschroder** [comment]
Heyy,

It doesnt work, AP- IP range is then set to an class B network. My test network is an class B. I already checked with all class types and read about how the AP can't have the same IP-Class as the Shared network if you want internet connection.

**Here is the IPtables with an class A Address range(Different IP class then my own network)**
└─$ sudo iptables -t nat -L 
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere    



**Here is the IPtables with an class B Address range(Same IP class as my own network)**
└─$ sudo iptables -t nat -L
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere     



**Here is the IPtables with an class C Address range(Different IP class then my own network)**
└─$ sudo iptables -t nat -L
# Warning: iptables-legacy tables present, use iptables-legacy to see them
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere            
                                                   



when stopping the AP i get an error message:
[-] socket error: [Errno 9] Bad file descriptor

just in case it means something.

Thanks for helping.

**Comment by mh4x0f** [comment]
```
[-] socket error: [Errno 9] Bad file descriptor
```

this error come from the dnsserver it not interfere on the share internet connection.

so, the problem is come from your system have some config the not match and allow to share  internet connection. 
This bug not come from the wp3.

The last option for try is using the dhcpdserver if dhcpserver not working i dont have option for solve your problem.
