### ISSUE TITLE
[bug] wrong sytnax causes wp3 to crash

### ISSUE THREAD

**Issue by itshimbuga** [P0cL4bs/wifipumpkin3#25]
**To Reproduce**
1. run wp3
2. set plugin kerberos
3. See error

> wp3 > set plugin kerberos
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/servers/mitm/mitmmode.py", line 92, in parser_set_plugin
>     plugin_name, plugin_status = list(args.split())[1], list(args.split())[2]
> IndexError: list index out of range
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/wifipumpkin3", line 11, in <module>
>     load_entry_point('wifipumpkin3==1.0.0', 'console_scripts', 'wifipumpkin3')()
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__main__.py", line 102, in main
>     prompt.cmdloop("Starting prompt...")
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 43, in cmdloop
>     super(ConsoleUI, self).cmdloop(intro="")
>   File "/usr/lib/python3.8/cmd.py", line 138, in cmdloop
>     stop = self.onecmd(line)
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/common/terminal.py", line 149, in onecmd
>     Cmd.onecmd(self, command)
>   File "/usr/lib/python3.8/cmd.py", line 217, in onecmd
>     return func(arg)
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/__init__.py", line 394, in do_set
>     return getattr(self.parser_list_func[func], func)(value, args)
>   File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/servers/mitm/mitmmode.py", line 108, in parser_set_plugin
>     return self.help_plugins()
> AttributeError: 'Sniffkin3' object has no attribute 'help_plugins'

* Wifipumpkin3 v1.0
* Virtual Machine (yes or no and which):  yes
* Operating System: kali
* version: 2020.1

**Comment by mh4x0f** [comment]
thank's for report :).
