### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Rehan919** [P0cL4bs/wifipumpkin3#250]
File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: install_layout

**Comment by Chydnoy** [comment]
pip install -U setuptools
pip install ujson
sudo pip install -U setuptools
pip install --upgrade --force-reinstall setuptools
Do this commands

**Comment by Rehan919** [comment]
Thanks a lot
