### ISSUE TITLE
Where are creds from captive portal logged?

### ISSUE THREAD

**Issue by cobra-c313** [P0cL4bs/wifipumpkin3#251]
I was wondering if there is some logic in wp3 to log creds from sniffing and captive portals or if it has to be created yet.
if it's not a feature yet, I would like to create a function to log creds as if there is lots of traffic on the ap, it will be hard to keep track. 
thanks for reading, any help will be appreciated

**Comment by mh4x0f** [comment]
doc -> https://wifipumpkin3.github.io/docs/configuration/log-file
