### ISSUE TITLE
Cannot build the Docker image

### ISSUE THREAD

**Issue by cosad3s** [P0cL4bs/wifipumpkin3#254]
**Description of the bug or feature request**

Cannot build the Docker image.

**To Reproduce**

1. `git clone https://github.com/P0cL4bs/wifipumpkin3.git`
2. `cd wifipumpkin3/`
3. `docker build -t "wifipumpkin3" .` the after a while:

```bash
1.285 Extracting wifipumpkin3-1.1.7-py3.7.egg to /usr/local/lib/python3.7/dist-packages
1.496 Adding wifipumpkin3 1.1.7 to easy-install.pth file
1.497 Installing captiveflask script to /usr/local/bin
1.497 Installing evilqr3 script to /usr/local/bin
1.497 Installing phishkin3 script to /usr/local/bin
1.497 Installing sslstrip3 script to /usr/local/bin
1.498 Installing wifipumpkin3 script to /usr/local/bin
1.498 Installing wp3 script to /usr/local/bin
1.498 
1.498 Installed /usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.1.7-py3.7.egg
1.498 Processing dependencies for wifipumpkin3==1.1.7
1.592 Searching for zope-interface>=5
1.592 Reading https://pypi.python.org/simple/zope-interface/
2.008 No local packages or working download links found for zope-interface>=5
2.008 error: Could not find suitable distribution for Requirement.parse('zope-interface>=5')
------
Dockerfile:29
--------------------
  27 |     RUN python3.7 -m pip install pyqt5==5.14
  28 |     RUN python3.7 -m pip install -r requirements.txt 
  29 | >>> RUN python3.7 setup.py install
  30 |     #CMD /usr/local/bin/wifipumpkin3 -m docker
  31 |     WORKDIR /root/.config/wifipumpkin3
--------------------
ERROR: failed to solve: process "/bin/sh -c python3.7 setup.py install" did not complete successfully: exit code: 1
```

**Expected behavior**

Docker build success.

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using: main branch ([d78cf31](https://github.com/P0cL4bs/wifipumpkin3/commit/d78cf3154692373a93a621eca0d975a054a5dd90))
* Virtual Machine (yes or no and which): NO
* Operating System: Kali
* version: `Linux kali 6.5.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux`

**Comment by mh4x0f** [comment]
@cosad3s hi, update the main branch and try again.

**Comment by mh4x0f** [comment]
i fix now, thanks again for report the bug. 

![image](https://github.com/P0cL4bs/wifipumpkin3/assets/6795613/9858be17-2a94-4722-bd21-e960194b04a2)

**Comment by cosad3s** [comment]
No problem, thanks, it perfectly builds now! :+1:
