### ISSUE TITLE
[kali Nethunter] AP is started and connectable but no internet for victim

### ISSUE THREAD

**Issue by dr1408** [P0cL4bs/wifipumpkin3#259]
**To Reproduce**
1. Go to Terminal
2. Run on wifipumpkin3 
3. I run it with set interface wlan1 which is my external adapter (tp link wn722n v3)  ..  set interface_net tried default and wlan0 .. always set proxy noproxy .. tried all dhcpconf 0,1,2 .. all dhcp mode (pydhcp,dhcpd) .. i didnt do any edit to hostapd.conf or resolv.conf

**Expected behavior**
Internet work on The AP

When i connect to ap it give me this output 
wp3 > start
[+] enable forwarding in iptables...
[*] sharing internet connection with NAT...
[*] setting interface for sharing internet: None
[+] starting hostpad pid: [25755]
wp3 > [+] hostapd is running
[*] starting pydhcp_server
[*] starting sniffkin3 port: [80, 8080]
[+] sniffkin3 -> emails     activated
[+] sniffkin3 -> ftp        activated
[+] sniffkin3 -> hexdump    activated
[+] sniffkin3 -> httpCap    activated
[+] sniffkin3 -> kerberos   activated

 [  pydhcp_server  ] 11:30:06  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('7a:81:43:5c:95:95')
        flags:
        hops: 0
        secs: 0
        xid: 843682240
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [X][051] ip_address_lease_time: 7776000
        [-][053] dhcp_message_type: DHCP_DISCOVER
        [-][055] parameter_request_list: 051:ip_address_lease_time, 053:dhcp_message_type
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][061] client_identifier: [378, 33091, 23701]

 [  pydhcp_server  ] 11:30:07  - DISCOVER: packet from 172.16.0.101
 [  pydhcp_server  ] 11:30:07  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('7a:81:43:5c:95:95')
        flags:
        hops: 0
        secs: 0
        xid: 843682240
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('172.16.0.101')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.240.0.0')
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_OFFER
        [X][054] server_identifier: IPv4Address('172.16.0.1')

 [  pydhcp_server  ] 11:30:07  - RECV from ('0.0.0.0', 68):
::Header::
        op: BOOTREQUEST
        hwmac: MAC('7a:81:43:5c:95:95')
        flags:
        hops: 0
        secs: 1
        xid: 843682240
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('0.0.0.0')
        sname: ''
        file: ''

::Body::
        [ ][050] requested_ip_address: IPv4Address('172.16.0.101')
        [-][053] dhcp_message_type: DHCP_REQUEST
        [X][054] server_identifier: IPv4Address('172.16.0.1')
        [-][055] parameter_request_list: 053:dhcp_message_type, 054:server_identifier
        [ ][057] maximum_dhcp_message_size: 1500
        [ ][061] client_identifier: [378, 33091, 23701]

 [  pydhcp_server  ] 11:30:08  - REQUEST: packet from 172.16.0.101 to 172.16.0.1
[*] 7a:81:43:5c:95:95 client join the AP
 [  pydhcp_server  ] 11:30:08  - SEND to ('0.0.0.0', 68):
::Header::
        op: BOOTREPLY
        hwmac: MAC('7a:81:43:5c:95:95')
        flags:
        hops: 0
        secs: 0
        xid: 843682240
        siaddr: IPv4Address('0.0.0.0')
        giaddr: IPv4Address('0.0.0.0')
        ciaddr: IPv4Address('0.0.0.0')
        yiaddr: IPv4Address('172.16.0.101')
        sname: ''
        file: ''

::Body::
        [X][001] subnet_mask: IPv4Address('255.240.0.0')
        [X][003] router: [IPv4Address('172.16.0.1'), IPv4Address('8.8.8.8')]
        [X][006] domain_name_servers: [IPv4Address('172.16.0.1')]
        [X][051] ip_address_lease_time: 7200
        [-][053] dhcp_message_type: DHCP_ACK
        [X][054] server_identifier: IPv4Address('172.16.0.1')

**Screenshots**

![Screenshot_20240404-134541_Photos](https://github.com/P0cL4bs/wifipumpkin3/assets/39735654/5f6ca480-5179-4a29-b4ed-ef6bd6e35fda)

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `Gao 1.1.7 main `).
* Virtual Machine (no): 
* Operating System: kali nethunter on android phone
* version: 2024.2

**Comment by dr1408** [comment]
![image](https://github.com/P0cL4bs/wifipumpkin3/assets/39735654/bba8fc0d-6791-42b2-8377-2ffcebf5cb22)

this with dhcp class B .. class a no rules and class c dosent connect because it is same ip range of my network that i use .. another difference i see between nethunter and people who use it in kali that when they run AP on kali it show additional note which is ( running py dns server on port 53 ) .. which is not the case with nethunter

**Comment by dr1408** [comment]
This result for captiveflask on class B also 

![image](https://github.com/P0cL4bs/wifipumpkin3/assets/39735654/3134bd71-2990-4dcc-81ba-51f70e31606a)


![image](https://github.com/P0cL4bs/wifipumpkin3/assets/39735654/919cc665-d928-4173-a148-029f3c0844c8)


Its not working though but will keep testing all posibilites

**Comment by dr1408** [comment]
![image](https://github.com/P0cL4bs/wifipumpkin3/assets/39735654/81dbadc7-9918-4d3a-8fc3-e99328b31b12)


This is after i set interface_net to wlan0 instead of default

**Comment by yesimxev** [comment]
@dr1408 what's your iptables version?

**Comment by dr1408** [comment]
> @dr1408 what's your iptables version?

The downgraded version 1.6.2 i think
