### ISSUE TITLE
Why does it always show "client has left AP" after I start it, and my mobile phone always automatically disconnects from the WiFi connection.

### ISSUE THREAD

**Issue by skr-rks** [P0cL4bs/wifipumpkin3#265]
Before opening a new issue, please make sure the issue you are reporting has not been reported before or is not included in the FAQ list on the website.

**Description of the bug or feature request**
My phone keeps disconnecting automatically after connecting to wifi
A clear and concise description of the error.
Every time it connects, it disconnects after two or three seconds. The terminal will show that my phone is connected, but it disconnects immediately.
**Reproduce**
1. Go to "..."
2. Run on "...."
3. See the error

**Expected behavior**
A clear and concise description of what you expect to happen.

**Screenshot**
If applicable, please add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/bb188657-f32b-4ce6-8daf-b6c57fdca7cb)
![image](https://github.com/user-attachments/assets/f9b98323-cf98-439d-893e-ed5e8ce5a47a)
![image](https://github.com/user-attachments/assets/e96f503f-50e5-47ec-9245-29b3ded6b3e1)

**Desktop (please fill in the following information): Windows 11 23H2
* The version of Wifipumpkin3 you are using (`version: 1.1.7 main`).
* Virtual Machine (yes or no and which one): VMware® Workstation 17 Pro
* Operating System: Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux
* Version:

** Incomplete reports will be closed *

**Comment by mh4x0f** [comment]
@skr-rks  checkout this settings can solve the problem.

https://github.com/P0cL4bs/wifipumpkin3/issues/158#issuecomment-1321331100

**Comment by Obb70** [comment]
[Uploading Motion free Free Freehak.xlsx…]()
