### ISSUE TITLE
Unnable to install in Kali Linux runing on Raspberry pi 3B

### ISSUE THREAD

**Issue by janesteban** [P0cL4bs/wifipumpkin3#28]
I follow wthe instruction son the [installation guide](https://wifipumpkin3.github.io/docs/getting-started#installation-procedure). All goes well until i execute the installer: $ sudo python3 setup.py install. The installation is done on a clean new kali linux, the version for raspberry pi3. Version: 2020.1a 64bits

The installation finishes with a fatal error. With the follwing message:
Searching for lxml>=4.5.0
Reading https://pypi.org/simple/lxml/
Downloading https://files.pythonhosted.org/packages/39/2b/0a66d5436f237aff76b91e68b4d8c041d145ad0a2cdeefe2c42f76ba2857/lxml-4.5.0.tar.gz#sha256=8620ce80f50d023d414183bf90cc2576c2837b88e00bea3f33ad2630133bbb60
Best match: lxml 4.5.0
Processing lxml-4.5.0.tar.gz
Writing /tmp/easy_install-df3mn2fn/lxml-4.5.0/setup.cfg
Running lxml-4.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-df3mn2fn/lxml-4.5.0/egg-dist-tmp-tm325u19
Building lxml version 4.5.0.
Building without Cython.
ERROR: b'/bin/sh: 1: xslt-config: not found\n'
** make sure the development packages of libxml2 and libxslt are installed **

Using build configuration of libxslt 
In file included from src/lxml/etree.c:692:
src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
   14 | #include "libxml/xmlversion.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compile failed: command 'aarch64-linux-gnu-gcc' failed with exit status 1
/tmp/easy_install-df3mn2fn/lxml-4.5.0/temp/xmlXPathInitsh_phf6p.c:1:10: fatal error: libxml/xpath.h: No such file or directory
    1 | #include "libxml/xpath.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************
error: Setup script exited with error: command 'aarch64-linux-gnu-gcc' failed with exit status 1`

Any one knows what is happening?

**EDIT**
As the error suggests i installed libxml2-dev and libxslt-dev using
sudo apt-get install libxml2-dev
sudo apt-get install -y libxslt-dev

Now no error is shown, but the raspberry pi freezes at:
```
Running lxml-4.5.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-d0muj
k4sl/lxml-4.5.0/egg-dist-tmp-aioh0g4l
Building lxml version 4.5.0.
Building without Cython.
Using Build configuration oflibxslt 1.1.32 
```

**Comment by mh4x0f** [comment]
try this:
``` sh
sudo apt-get install -y python3-lxml
```
