### ISSUE TITLE
Function add request:Respond to probe requests to detect open Wi-Fi

### ISSUE THREAD

**Issue by LuckyFishGeek** [P0cL4bs/wifipumpkin3#29]
Respond to probe requests to detect+captive portal

Similar  The pineap function of WiFiPineapple device

Happy life

 forgive me for my poor English ,Please

**Comment by mh4x0f** [comment]
did you can explain more or send me one example ? I really want to know that feature is this

**Comment by LuckyFishGeek** [comment]
@mh4x0f 
Official notes on the function of pineap:
https://docs.hak5.org/hc/en-us/articles/360010555253-The-PineAP-Suite

I will send you a video in a few days to see this function implemented with the Raspberry Pi!

The approximate function is:

First detect the wifi AP that all smart devices nearby have connected to

Then fully simulate these APs and broadcast them, similar to karma attack!

Finally trick these devices to automatically or actively connect to these open APs, and then pop up a mandatory portal


My English is very bad, the description is inaccurate or the language offends my brother,  understand me,please.....

**Comment by mh4x0f** [comment]
@LuckyFishGeek the Karma attack I'll add coming soon as a feature, I think that this feature listed by hack5 is possible because Pineapple run on custom linux, it more simple to change the hostapd and implement this features. The WP3 this is not possible because run on debain, archlinux, wifislax and more OS. it very complicate to compile this feature that work fine and all system.

**Comment by LuckyFishGeek** [comment]
@mh4x0f You can take a look at this project, this is a tool I used to find someone to imitate the function of PineAP
https://github.com/Geeks-alliance/karma-captive-portal

**Comment by mh4x0f** [comment]
I'll check this

**Comment by LuckyFishGeek** [comment]
Thank you for making such a good tool. I want to help you promote it on the Internet in China!
Have a good life

**Comment by mh4x0f** [comment]
> I still don't understand how they do to use multiple SSID with the same wifi spot... In the end wifi pumkin is only a package of freetools...

it simple, when you active your wifi android or desktop whatever device, he check if the network that you are connected time ago is visible, this is called the Probe request attack. basic, the device device send Probe request packet, this is packet is captured by hostapd (software that mout the AP) and send another type packet with SSID that your device is try to connected. I'll make a paper more details about that coming soon. 

> Any way, I'm watchin wifi pumkin since a long time, I'm very happy to see this new version !
Thank you mh4x0f !

thank's,  so I hope is gonna helpful.
