### ISSUE TITLE
captiveflask options multi language templates

### ISSUE THREAD

**Issue by samaelscl** [P0cL4bs/wifipumpkin3#30]
Hello, I am using Kali version 2020.2 over VMWare 15 with an Alpha Network adapter. The app works well, but I have a problem, when trying to change "portal" (captiveflask) in the Proxies section, it is not reflected in the computers or phones. I Try 4 different devices and in all of them you see the same portal presentation, I tried all of them and the same authentication page continues to appear. On the other hand, the captiveflask template "Dark" is always auto-setting, so I modified the HTML, just one word, to see if the change was reflected in the devices and it didn't work either.

I uninstalled wifipumpkin, I re-installed it and deleted the templates in different folders that are generated, when I re-installed, the same thing happened, I cannot change the portal.

![01](https://user-images.githubusercontent.com/64997057/81360360-e73d1900-90db-11ea-8cda-a94d3e86f9d9.JPG)

![Screenshot_20200508-031709_CaptivePortalLogin](https://user-images.githubusercontent.com/64997057/81360372-ec9a6380-90db-11ea-87ce-9f5308f1c324.jpg)

**Comment by mh4x0f** [comment]
hi @samaelscl  thank's for report, good report. I found a bug on **FlaskDemo** plugin in the **captiveflask**, but all other plugins is working fine for me.  I'll fix this problem with FlaskDemo coming soon. did you try that with another plugins like **Login_v4, loginPage** ?

**Comment by samaelscl** [comment]
Hi!, Yes. The truth is that I think the bug is perhaps with Kali or the application. What I managed to detect is that the portals do not change unless you restart the machine. I made some changes in HTML as I told you, restart the virtual machine and the changes were reflected, but yes, I need restart the machine.

**Comment by mh4x0f** [comment]
but you not need to restart the machine, but you can restart the accesspoint when change the captiveflask plugins. btw, I'll fix the bug with **FlaskDemo** and now you can use the plugins for create a custom page. I'll also make a video coming soon how to create a captiveflask template.

**Comment by samaelscl** [comment]
Hello!, I tried restarting the access point, but it did not work, I have been about 5-6 hours with the problem trying to find the cache or see where the temporary information was stored so that I did not have to force a restart, I tried everything, but now that's it working!, even with new template!, I used the template of another application and it works wonderfully.
