### ISSUE TITLE
DHCP offer Apple device can’t connect to ap

### ISSUE THREAD

**Issue by Levple** [P0cL4bs/wifipumpkin3#32]
i have an issue with the connection between ap and device (in this case my mobile phone).
Installing wp3 and setting up the ap went pretty good, the ap is visible but my phone can’t connect to ap.
Every time I get a message “DHCP offer” in wp3 no matter which device I tried (iPhone, iPod)

![65A0B41A-0063-4790-A2E2-45995DC9D9A7](https://user-images.githubusercontent.com/64223848/81468855-500eb900-91e2-11ea-9272-aea9aba01e16.jpeg)

wifipumpkin3 v1.0.0
Virtual Machine (yes or no and which): no
Operating System: kali
version: 2020.1

**Comment by mh4x0f** [comment]
@Levple thank's for report this bug, **_HACK THE PLANET_*.
