### ISSUE TITLE
hostapd_free_hapd_data: Interface wlan0 wasn't started

### ISSUE THREAD

**Issue by agan19** [P0cL4bs/wifipumpkin3#33]
ile "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.0-py3.8.egg/wifipumpkin3/core/wirelessmode/wirelessmode.py", line 134, in get_error_hostapdServices
    raise HostapdInitializeError(
wifipumpkin3.exceptions.errors.hostapdException.HostapdInitializeError: [ERROR] Hostpad Failed: check output process hostapd.
 Configuration file: /root/.config/wifipumpkin3/config/hostapd/hostapd.conf
rfkill: WLAN soft blocked
wlan0: Could not connect to kernel driver
Using interface wlan0 with hwaddr bc:f6:85:03:36:5b and ssid "ddemo"
Failed to set beacon parameters
wlan0: Could not connect to kernel driver
Interface initialization failed
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: Unable to setup interface.
wlan0: interface state DISABLED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
Aborted
This is what im getting...
Wifipumpkin version - latest
OS : Kali linux latest
VM: No

**Comment by mh4x0f** [comment]
I fix it unblocking the wifi adapter:
``` bash
sudo rfkill unblock wifi
```
You can check the blocking status with:
``` sh
rfkill list
```
font: https://github.com/ct-Open-Source/tuya-convert/issues/139

**Comment by cyrxdzj** [comment]
I think this article can solve this problem.
However, this article is written in Chinese.
[https://www.cnblogs.com/dakewei/p/5735141.html](https://www.cnblogs.com/dakewei/p/5735141.html)
