### ISSUE TITLE
scapy_http: dead project

### ISSUE THREAD

**Issue by blshkv** [P0cL4bs/wifipumpkin3#35]
wifipumpkin3 requires this package but the project is dead:

https://github.com/invernizzi/scapy-http
Please consider this package as obsolete - long live Scapy!

Please migrate

**Comment by mr007guy** [comment]
How would one actually use wifipumpkin to an advantage if hsts basically made 90 mostly 100 percent of mitm scripts useless.

**Comment by mh4x0f** [comment]
I find on scapy repository and the support native is on release version. [scapy thread](https://github.com/secdev/scapy/pull/1925#issuecomment-509185642)

I 'm wait for a stable version, like 2.4.4 for  remove scapy_http.

**Comment by blshkv** [comment]
Please keep it open until it is fixed

**Comment by blshkv** [comment]
I have review the pull request. It is in the scapy 2.4.3 already, partially at least. Can you try it?

**Comment by mh4x0f** [comment]
@blshkv  no, 2.4.3 not have this implementation.

**Comment by blshkv** [comment]
It is merged, no? Look at the source code.

**Comment by mh4x0f** [comment]
@blshkv yes, it is merged but the version 2.4.3 no have this implementation as you can see on comment, it is on pre-release. I found the version 2.4.4 but is pre-release, it not recommanded to add a pre-release as depedencies.

**Comment by blshkv** [comment]
As I said, dont just guess, check the source code. It is there, both 2.4.3 and 2.4.4_rc1 got it.

**Comment by gpotter2** [comment]
Hi, 2.4.4 was released: https://pypi.org/project/scapy/2.4.4/
