### ISSUE TITLE
requirements.txt are too strict

### ISSUE THREAD

**Issue by blshkv** [P0cL4bs/wifipumpkin3#36]
Hello,

I'm packaging this tool to Pentoo Linux and trying to resolve dependencies between different packages. I discovered that many dependencies are listed with a specific version using ```==```.
This seems unnecessary and it's hard to deal when two such software require a similar package (for example xyz==1.2.3 and xyz==1.2.4). Please use >= if it is really required or do not specify a version at all.

**Comment by mh4x0f** [comment]
I following the python documentation package pip, the recomendation  is lock specific version.

**Comment by blshkv** [comment]
Can you give me a reference to the documentation? I do not think this is mandatory.
You can specify 'pkg>=1.2.0,<1.3.0' if this package is known to break compatibility, or pkg>=1.2.0 if you use some specific feature introduced in that version. But it is not required in general

**Comment by mh4x0f** [comment]
@blshkv I 'll do somes updates on requirements.txt, because I had an issue report. I 'll apply this modification.

**Comment by blshkv** [comment]
Thanks, but you missed twisted==19.7.0

**Comment by mh4x0f** [comment]
this version not to be change

**Comment by blshkv** [comment]
Ok, thanks for looking at it
