### ISSUE TITLE
After a while, the AP cannot connect

### ISSUE THREAD

**Issue by LuckyFishGeek** [P0cL4bs/wifipumpkin3#37]
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).  wifipumpkin3 v1.0.0
* Virtual Machine (yes or no and which): vm
* Operating System:kali 
* version: 2020.2

Test device: 
Android:   nexus 6p
IOS: iphone4 IOS6
       iphone5s IOS12

![Snipaste_2020-05-16_14-53-56](https://user-images.githubusercontent.com/29472751/82113022-34c52000-9785-11ea-82ea-5e55ca17728e.png)

And the AP will disappear, unable to connect

![1589612120921](https://user-images.githubusercontent.com/29472751/82113068-8f5e7c00-9785-11ea-9556-6c7e827176b2.jpg)

**Comment by mh4x0f** [comment]
full updated with branch dev, try with current dev branch updates

**Comment by LuckyFishGeek** [comment]
i will try it then submit a report    ,thanks

**Comment by LuckyFishGeek** [comment]
@mh4x0f 

Manual update to the latest version, the same problem!

Can only connect once, then it will automatically disconnect, and then the AP will disappear
![Snipaste_2020-05-24_21-16-32](https://user-images.githubusercontent.com/29472751/82755134-443b0d80-9e04-11ea-9c74-78b4bede7924.png)

**Comment by mh4x0f** [comment]
did you try with another proxy activated ? like pumpkinproxy or noproxy ? 
check this also

**Comment by mh4x0f** [comment]
@LuckyFishGeek I add a patch for try to fix the bug, but I tested in my lab and work fine.  send me feedback !
