### ISSUE TITLE
[Errno 98] Address already in use

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#38]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

i have stopped port 53 before proceeding. 

Starting prompt...
wp3 > set interface wlan0
wp3 > set ssid connecthere
wp3 > set proxy noproxy
wp3 > start
[+] enable forwarding in iptables...
SIOCADDRT: File exists
[*] sharing internet connection with NAT...
[+] starting hostpad pid: [5138]
[*] starting pydhcp_server
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.0-py3.7.egg/wifipumpkin3/core/packets/dnsserver.py", line 272, in run
    self.resolver, port=port, logger=self.logger_dns, tcp=True
  File "/usr/local/lib/python3.7/dist-packages/dnslib-0.9.7-py3.7.egg/dnslib/server.py", line 343, in __init__
    self.server = server((address,port),handler)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
Aborted

**To Reproduce**
1. set interface, set ssid, set proxy, start

**Expected behavior**
AP starts without error

**Screenshots**

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( 1.0.0 dev).
* Virtual Machine (no): 
* Operating System: Parrotsec
* version: 5.4

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by LESP1NK** [comment]
I had the same issue (in the same environments) until i've removed any conf of AP with hostapd...

**Comment by mh4x0f** [comment]
read: https://wifipumpkin3.github.io/docs/getting-started#based-on-debian-procedure
