### ISSUE TITLE
TABLE_ADD failed

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#41]
**Description of the bug or feature request**

iptables v1.8.3 (nf_tables): TABLE_ADD failed (invalid argument): table filter

**To Reproduce**
1. wifipumpkin3
2. set interface wlan1, set ssid test, set proxy noproxy
3. See error

**Expected behavior**

should be able to connect to AP and starts without error.

**Screenshots**
[+] enable forwarding in iptables ...
[*] sharing internet connection with NAT...
**iptables v1.8.3 (nf_tables): TABLE_ADD failed (invalid argument): table filter**
[+] starting hostapd: [8830]
[*] starting pydhcp_server
wp3 > [*] starting sniffkin3 port: [80, 8000]
[+] sniffkin3 -> emails activated
[+] sniffkin3 -> ftp
[+] sniffkin3 -> hexdump
[+] sniffkin3 -> httpCap
[+] sniffkin3 -> kerberos

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( 1.0.0 dev).
* Virtual Machine (no): 
* Operating System: linux kali
* version: 2019.4

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by jepunband** [comment]
ok, fixed it by changing iptables-nft  to iptables-legacy , it works now.

**Comment by mh4x0f** [comment]
https://wifipumpkin3.github.io/docs/getting-started#requirements
