### ISSUE TITLE
Please set a tag version at the base image in Dockerfile 

### ISSUE THREAD

**Issue by rafonsecad** [P0cL4bs/wifipumpkin3#43]
**Docker setup failed due to the new ubuntu 20.04 image**

There is a new ubuntu LTS version (20.04), which is going to be downloaded by default in the Dockerfile instead of the 18.04 version. This causes that some packages won't be found and the docker container set up will fail.

To avoid this issue please set a tag version in the Dockerfile
`FROM ubuntu:18.04`

**Reproduce the issue**
1. Checkout to dev branch
2. docker build -t "wifipumpink3" .
3. After finding the packages, it won't find python3.7-dev. This package no longer exists in ubuntu 20.04, the following error message appears:

E: Unable to locate package python3.7-dev
E: Couldn't find any package by glob 'python3.7-dev'
E: Couldn't find any package by regex 'python3.7-dev'

**Expected behavior**
Install correctly the packages included in the Dockerfile

* Wifipumpkin3 version: 8b064982f2f51f48fbcad21f4a3b509e4a5ce623
* Virtual Machine (yes or no and which): No
* Operating System: Ubuntu 20.04

**Comment by mh4x0f** [comment]
nice issue, thank's for report this. I'll fix this next push request.
