### ISSUE TITLE
Not binding to port 53 - PyDNS (Kali Nethunter)

### ISSUE THREAD

**Issue by f0unix** [P0cL4bs/wifipumpkin3#46]
I tested the wifipumpkin3 module over a Kali VM and it works flawlessly, however on Kali Nethunter (Nexus 6) it show it's running, the fake AP is being created but there are no redirects to captiveflask plugins. reproduced same steps on a Kali VM works just well and fine no problems. 

I checked my netstat after running both tests over Kali Linux VM and Kali Nethunter Nexus 6, port 53 is clearly not opening with wifipumpkin3.

Screenshots from Kali Nethunter on Nexus6

![1Capture](https://user-images.githubusercontent.com/2315629/83391629-0df92180-a3f4-11ea-8e55-027c4a11d69a.PNG)
![2Capture](https://user-images.githubusercontent.com/2315629/83391632-0e91b800-a3f4-11ea-8fac-95a9cb8331bf.PNG)
![3Capture](https://user-images.githubusercontent.com/2315629/83391633-0f2a4e80-a3f4-11ea-9236-1ce53d972cc2.PNG)

**Comment by mh4x0f** [comment]
hi, send me the output of command bellow,  when ap is running on kali nethunter. I suposed that something wrong with iptables command.
``` sh
sudo iptables -t nat -L
```
obs: in the first screenshot that you send to me say:
``` 
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```
I search on google about this bug and I discovery that iptables is already busy executing another command. so, I recommand to try the solution is [iptables bug](https://serverfault.com/questions/935272/another-app-is-currently-holding-the-xtables-lock).  btw, if you need to change any commnad iptables should be executed by tool, check this [doc configuration](https://wifipumpkin3.github.io/docs/configuration/configuration-file#configuration-structure) and search about `config.ini` file, it have all rules from iptables execute in background.

**Comment by f0unix** [comment]
thank you for reply the results are the following.

these are the results, I think it's something related to the kernel I am using ! but if you have a possible solution that might help ! 

iptables 
![aaa](https://user-images.githubusercontent.com/2315629/83892122-804c6780-a74e-11ea-93c2-c5ac6008fd1c.PNG)
netstat 
![bbbb](https://user-images.githubusercontent.com/2315629/83892127-80e4fe00-a74e-11ea-88ef-d6971076043f.PNG)

**Comment by mh4x0f** [comment]
what is say when you join the AP ?

**Comment by jepunband** [comment]
hi .. i have the same results, eveyrthing starts up normal, no errors. client can connect to AP, but no redirect. on client device it says Internet may not be available.

**Comment by xpz3** [comment]
In nethunter, use iptables v 1.6. For a proper fix, add support for nftables @mh4x0f

**Comment by jepunband** [comment]
@xpz3 where can i find and install iptables v 1.6 ?

**Comment by xpz3** [comment]
> @xpz3 where can i find and install iptables v 1.6 ?

https://ubuntu.pkgs.org/18.04/ubuntu-main-arm64/iptables_1.6.1-2ubuntu2_arm64.deb.html
this is for arm64 and not armhf

**Comment by dr1408** [comment]
I tried on nethunter with iptables 1.6 same outputs but without error another app is holding xtables lock .. still no internet shared and no captive portal any one using nethunter got it fixed ?
