### ISSUE TITLE
hostapd is not installed in the system

### ISSUE THREAD

**Issue by sudo-techy** [P0cL4bs/wifipumpkin3#53]
when I input the start command to start the access point I always ran into this problem "hostapd is not installed in the system"
![Screenshot 2020-06-19 03:54:45](https://user-images.githubusercontent.com/55027865/85078213-8b3cd880-b1e1-11ea-81d3-8bda7613f629.png)

version using :- Wifipumpkin3 - v1.0.5 "AKUANDUBA"
Virtual Machine : yes, vmware fusion
Operating System: Kali linux 2020.2

**Comment by mh4x0f** [comment]
please read the [documentation guide]( https://wifipumpkin3.github.io/docs/getting-started#requirements).
the **wp3** need to hostapd installed by default, follow the command bellow hot to install it.

``` sh 
sudo apt-get install hostapd
```
