### ISSUE TITLE
remove username/email input <Captiveflask>

### ISSUE THREAD

**Issue by fenterprises** [P0cL4bs/wifipumpkin3#59]
I tried to remove the username input field of the html file but the wifipumpkin3 does not accept one input from the user when the AP is generated. 
I've tried to fix the issue but no luck

**To Reproduce**
1. Go to 
wifipumpkin3>config>templates
2. Run on 
Kali Linux

**Comment by mh4x0f** [comment]
> I tried to remove the username input field of the html file but the wifipumpkin3 does not accept one input from the user when the AP is generated.

by default the captiveflask module need to input username for allow to access the internet, 

>Go to wifipumpkin3>config>templates

if you want to edit the html files, you need to go on `.config/wifipumpkin3/config/templates/` on home directory, as you can see on [documentation](
https://wifipumpkin3.github.io/docs/getting-started#include-the-templates).

**Comment by fenterprises** [comment]
Working wonderfully, Great project. Thank you for the help.
