### ISSUE TITLE
Socket error: 'Unassigned'

### ISSUE THREAD

**Issue by Mathostx** [P0cL4bs/wifipumpkin3#60]
**To Reproduce**
There really isn't anything specific other than installing (successfully) and running the ap.

I'm getting this error and devices wont connect. 
I tried switching to noproxy (80) / pumpkinproxy (8080)

AP appears but as soon as I try to connect:

**Expected behavior**
[-] socket error: 'Unassigned'
[-] socket error: 'Unassigned'
[-] socket error: 'Unassigned'
[-] socket error: 'Unassigned'

Any ideas???

**Desktop Kali 2020
* Wifipumpkin3 version version: 1.0.5 
* Virtual Machine (yes or no and which):  VMWARE Workstation Pro.
* Operating System: Kali Linux / Win10

**Comment by mh4x0f** [comment]
I can't to reproduce this bug, which command did you use to start the tool and you have log ? with this report I can't find anythink
