### ISSUE TITLE
[Request] set ssid with blank spaces

### ISSUE THREAD

**Issue by rafonsecad** [P0cL4bs/wifipumpkin3#62]
From what I've seen so far, setting any ssid with blank spaces won't set the whole ssid but only the first word.

**To Reproduce**
1. On the terminal type `$ wifipumpkin3`
2. type any ssid with spaces, i.e., `$ set ssid "network 1"`
3. wifipumpkin will only recognize the first word as the name of the network, in this case `"network`

**Expected behavior**
It would be very convenient to include the whole name of the network in the ssid field. The only workaround I know is to edit directly the config.ini file before wifipumpkin3 is executed.

My guess to include this feature is a change in wifipumpkin/core/common/terminal.py file, specifically, the function `do_set`

```python
    def do_set(self, args):
        """ set options for module """
        try:
            command, value = args.split()[0], args.split()[1]
```

As we can see above, `command` and `value` are both set after a split, so we can change the way `value` has its value by first looking if there is a pair of double quotes, otherwise take the value of `args.split()[1]`. I tried to implement such features but I got confused creating the unit test. 

Thanks for reading this

* Virtual Machine (yes or no and which): Docker version
* Operating System: Ubuntu 20.04
* version: 8e12ef350201fb394036f509c78115f685f5d725

**Comment by mh4x0f** [comment]
I pushed a solution, but I should be add a validator for ssid, like can see on hostapd documentation. btw, tthank's for nices reports.
