### ISSUE TITLE
client has left AP 

### ISSUE THREAD

**Issue by crypto-png** [P0cL4bs/wifipumpkin3#67]
Client disconnects from access point after 5-10 minutes  connection (console displays:client has left AP) . After that, it is impossible to connect to the access point, even after re-entering the password. What could be the problem?
Wifipumpkin version: 1.0.7
The virtual machine is not used.
OS: Kali Linux

"hostnamectl" command:
 Kernel: Linux 5.4.0-kali3-amd64
 Architecture: x86-64

"cat /etc/os-release" command:
VERSION="2020.3"

**Comment by ShironNorihs** [comment]
Yea, i have the same issue with same version of Kali Linux.
I am using Raspbery pi 4 with network adapter TP-LINK WN722N.

**Comment by realtaotao1984** [comment]
是的，同样的问题。搞了3天。才知道，大家都是这问题。

**Comment by mh4x0f** [comment]
hi all, the hostapd tool by default is 300 s or 5 min to inactivity client connected on ap, look the config 
```
# The station can associate again with the AP if it is still in range;
# this inactivity poll is just used as a nicer way of verifying
# inactivity; i.e., client will not report broken connection because
# disassociation frame is not sent immediately without first polling
# the STA with a data frame.
# default: 300 (i.e., 5 minutes)
#ap_max_inactivity=300
```
I 'll change this coming soon and maybe include more options on config.ini but if you want to set manually you can change the code.

**Comment by realtaotao1984** [comment]
我连接上，一直刷QQ，还是掉啊。难道是我的kailinux版本太高了？ 我用的2020.3的镜像，2020.1的镜像我也适用过。问题依旧。

**Comment by realtaotao1984** [comment]
难道是我的kailinux版本太高了？ 我用的2020.3的镜像，2020.1的镜像我也适用过。问题依旧。

**Comment by mh4x0f** [comment]
please, only english here

**Comment by mh4x0f** [comment]
ok, gys now I add a new default value por inactivity poll when the AP is runnning after 60 min you can be desconncted from AP. but you can change this value on file config.ini follow the guide on wp3 documentation [config files](https://wifipumpkin3.github.io/docs/configuration/configuration-file)

**Comment by kattymm** [comment]
i still don‘t konw how to solve it ,please tell me details.

**Comment by kanadeblisst** [comment]
wifipumpkin3 v1.0.8 branch: dev

ap_max_inactivity is 3600 ,  But there is also the problem

**Comment by Gits3** [comment]
I have this problem on the latest wifipumpkin3

**Comment by exactsameproblem** [comment]
Hello, I have the latest version (2022) and even with the 3600s timeout, the problem is still here. Tried with kali and wifipumpkin3, either a smartphone or laptop, they always get disconnected "client left AP" after only some minutes, and it becomes impossible to join back the AP 'cannot connect to AP'.

**Comment by mvthul** [comment]
Anyone found the problem?

**Comment by mh4x0f** [comment]
the solution is:  https://github.com/P0cL4bs/wifipumpkin3/issues/158#issuecomment-1321331100
