### ISSUE TITLE
SyntaxWarning: 'str' object is not callable

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/wifipumpkin3#69]
**Description of the bug or feature request**

**To Reproduce**
1. sudo wifipumpkin3
2. See error ..

**Expected behavior**
no syntax error.

**Screenshots**
sudo  wifipumpkin3

/usr/local/lib/python3.8/dist-packages/ipaddress-1.0.22-py3.8.egg/ipaddress.py:1106: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
  raise TypeError("%s and %s are not of the same version" (a, b))

  _      ___ _____     ___                  __    _      ____
 | | /| / (_) __(_)___/ _ \__ ____ _  ___  / /__ (_)__  |_  /
 | |/ |/ / / _// /___/ ___/ // /  ' \/ _ \/  '_// / _ \_/_ < 
 |__/|__/_/_/ /_/   /_/   \_,_/_/_/_/ .__/_/\_\/_/_//_/____/ 
                                   /_/                       
                                            codename: nidavellir
Made by: @mh4x0f - P0cL4bs Team | 1.0.0 dev
[*] Session id: fc3946b2-dc49-11ea-b37d-c0eefb05c941 
Starting prompt...
wp3 > 

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `1.0.0 dev `). 
* Virtual Machine (no): 
* Operating System: Kali
* version: 2020.3

**Comment by mh4x0f** [comment]
send me the output of command: python3 --version

**Comment by jepunband** [comment]
Python 3.8.5

**Comment by mh4x0f** [comment]
Execute this command: 
``` sh
sudo pip3 install ipaddress==1.0.23
```
