### ISSUE TITLE
WiFiPumpkin3 crash after running custom pulp script

### ISSUE THREAD

**Issue by Avatar-TLA** [P0cL4bs/wifipumpkin3#75]
Hello again, coming up with a new issue!

**Description of the bug or feature request**

Made a pulp script file, and wp3 crashes after execute.

The script contains this code:
**set interface wlan0
set ssid Test WiFi
use misc.extra_captiveflask**

I save this script as **start_up.pulp** inside **/wifipumpkin3/scripts** folder.

And am running from root:~/wifipumpkin3# **wifipumpkin3 --pulp scripts/start_up.pulp**

The expected behavior is to run it, and live wp3 on state -> **wp3: extra_captiveflask >**
waiting for the next command.

It simply closes and brings me back to terminal (root@kali:~/wifipumpkin3#)

**(The issue, is the last command, use misc.extra_captiveflask. I executed the script without this command, and it runs smooth. I tried some other commands too, and they execute too. But when i type the command manually in wp3 > or when i have it in the script, it crashes.)**

**Desktop (please complete the following information):**
Wifipumpkin3 version: 1.0.7.
Virtual Machine (yes or no and which): no, Raspberry 4B
Operating System: Kali Linux
Version: 2020.3

Thank you in advance.

**Comment by stelladim** [comment]
Hello, 

I did the exact same thing as you and I have the same error. I wrote a pulp script with the commands **set interface wlan0**, **set ssid Evil Wifi** and when I'm in the wp3 and try to run the command **use misc.extra_captiveflask**, I got kicked from wp3 and I am brought back to root@kali.

In addition, when I run both the commands (**use wifi.wifideauth** and use **wifi.wifiscan**), I have the following error and after that I got kicked from wp3.
wp3 > use wifi.wifideauth 
[-] unknown command: ssid 
[*] Example : set host 127.0.0.1
root@kali:~# 

Thanks in advance!

**Comment by mh4x0f** [comment]
please read the doc, the if you use misc.extra_captiveflask , you should be return for main command with **back command** for after that you can run the command start.
