### ISSUE TITLE
Captiveflask not blocking internet access to user. Access point doesn't request verification.

### ISSUE THREAD

**Issue by stelladim** [P0cL4bs/wifipumpkin3#76]
Hello!

I’m having a problem with captiveflask. I followed the instructions of your youtube video [Facebook captive login templates with wifipumpkin3](https://youtu.be/0TPWLZ8_-mM) and when I set captiveflask plugin to any option, it doesn't open the verification window to user when he connects to the access point. The user though is connected to the access point and has internet access.

**Expected behavior
Captiveflask should block user from accessing the internet before his verification to the access point**

Desktop (please complete the following information):
Wifipumpkin3 version: 1.0.7.
Virtual Machine (yes or no and which): no, Raspberry 4B
Operating System: Kali Linux
Version: 2020.3

Thanks in advance!

**Comment by mh4x0f** [comment]
look the [doc](https://wifipumpkin3.github.io/docs/getting-started#requirements) , it possble that your iptables tool not is working on background to block the internet connection. if you want to check this, after execute the ap try to run the command:
``` sh
sudo iptables -t nat -L 
```
this command will be list all rules that the **wp3** setted for block the conection with internet. send me the output for more explain here.
