### ISSUE TITLE
Proxies not working

### ISSUE THREAD

**Issue by raf1312** [P0cL4bs/wifipumpkin3#82]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

**Description of the bug or feature request**

When setting a Proxy other than noproxy the script crashes after starting.

**To Reproduce**
set proxy captiveflask
set captiveflask.DarkLogin true
start

![image](https://user-images.githubusercontent.com/30720581/91663785-5c998300-eaeb-11ea-8c70-cb0cecd32820.png)

Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
Wifipumpkin 1.0.7
Virtual Machine: no

**Comment by trueToastedCode** [comment]
Unable to reproduce. I would recommend a reinstallation. Update the system with `sudo apt update && sudo apt dist-upgrade` before doing so.
