### ISSUE TITLE
"extra-captiveflask" "Creating Captive Portal template" have Error

### ISSUE THREAD

**Issue by u-u-u-u-u-u** [P0cL4bs/wifipumpkin3#83]
https://github.com/mh4x0f/extra-captiveflask#creating-captive-portal-template
https://wifipumpkin3.github.io/docs/getting-started#captiveflask

The last line :"     self.ConfigParser = Flase "
"Flase" X,"python3 setup.py install" will error
should "False",is right

**Comment by trueToastedCode** [comment]
Yes, the message is already telling that ;D
