### ISSUE TITLE
Failure during installation 

### ISSUE THREAD

**Issue by hakonamatata** [P0cL4bs/wifipumpkin3#85]
**Description of the bug or feature request**

I get this error when I run 

`
Traceback (most recent call last):
  File "/usr/local/bin/wifipumpkin3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5>=5.14' distribution was not found and is required by wifipumpkin3
`

I think the problem is because of the installation fails here:

**sudo python3 setup.py install**

`Installed /usr/local/lib/python3.7/dist-packages/wifipumpkin3-1.0.7-py3.7.egg
Processing dependencies for wifipumpkin3==1.0.7
Searching for PyQt5>=5.14
Reading https://pypi.org/simple/PyQt5/
Downloading https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz#sha256=c6f75488ffd5365a65893bc64ea82a6957db126fbfe33654bcd43ae1c30c52f9
Best match: PyQt5 5.15.0
Processing PyQt5-5.15.0.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-vbbz_kjj/PyQt5-5.15.0.tar.gz
`

**Comment by trueToastedCode** [comment]
Well, following the installation instruction, this dependency gets installed manually (kali linux):
`sudo apt install python3-pyqt5`
(check success) `python3 -c "from PyQt5.QtCore import QSettings; print('done')"`
-> `sudo python3 setup.py install`

**Comment by hakonamatata** [comment]
I followed all the instructions, python3-pyqt5 gets installed fine. It fails to install "PyQt5-5.15.0.tar.gz"

**Comment by hakonamatata** [comment]
Not sure why this is closed. Or marked as invalid. I used a fresh install of Ubuntu. Followed every installation instruction to the letter. Including the manuell installation of python3-pyqt5 mentioned above. Yet, the installation fails and the running the application gives an exception. This should clearly be fixed.

**Comment by kyawkyawsoezhu** [comment]
@hakonamatata I managed to solve the error by running these commands
`pip install wheel`
`pip install flask-jwt-extended`
