### ISSUE TITLE
Unable to complete setup on Kali 2020.3

### ISSUE THREAD

**Issue by nonewz** [P0cL4bs/wifipumpkin3#90]
Following the setup instruction for kali the setup runs and gets blocked after "searching for urwid==1.1.2". 
The setup is not finishing the task must be interrupted by CTRL+C.

![Parallels DesktopKali Linux2020-09-16 at 12 28](https://user-images.githubusercontent.com/36957720/93325808-27de3900-f818-11ea-9e1c-1bc127a0759e.jpg)

System version:
![Parallels DesktopKali Linux2020-09-16 at 12 29](https://user-images.githubusercontent.com/36957720/93325907-53f9ba00-f818-11ea-9ca3-ef2d462593e9.jpg)

wifipumpkin3 version: 1.0.7 Pulled from git on Sep 16.

Steps to reproduce:
Install Kali Linux in a VM (parallel desktop 16 on Mac).

 $ sudo apt install libssl-dev libffi-dev build-essential
 $ git clone https://github.com/P0cL4bs/wifipumpkin3.git
 $ cd wifipumpkin3

sudo apt install python3-pyqt5 (which was already there on the lastest Kali version (2020.3)

 $ sudo python3 setup.py install

After this, the setup runs for a while and then stops at the urwid installation.

**Comment by mh4x0f** [comment]
hi, good report. the temp solution is update the urwid version. go to edit the file **requirements.txt** change the version **urwid==1.1.2** for **urwid==2.1.1** and try re install :
``` sh 
sudo python3 setup.py install
```
if you got someone error, please report here.
