### ISSUE TITLE
RuntimeError: wrapped C/C++ object of type QProcess has been deleted

### ISSUE THREAD

**Issue by doctor99** [P0cL4bs/wifipumpkin3#93]
Please, before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the website FAQ list.

Running wifipumpkin3 1.0.7 on Kali 2020.3
When starting the wifipumpkin3 AP, the program crashes with the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifipumpkin3-1.0.7-py3.8.egg/wifipumpkin3/core/common/threads.py", line 237, in __del__
RuntimeError: wrapped C/C++ object of type QProcess has been deleted

**To Reproduce**
1. Installed successfully running sudo python3 setup.py install
2. Run wifipumpkin3 using sudo wifipumpkin3
3. At wf3> prompt type:
-- set interface wlan1
-- set ssid pumpkinwifi
-- set proxy noproxy
-- start
4. Program crashes with error above

**Desktop (please complete the following information):**
* Wifipumpkin3 version you are using ( `wifipumpkin3 --version `).  - 1.0.7
* Virtual Machine (yes or no and which):   No
* Operating System:  Kali Linux
* version:  2020.3

** INCOMPLETE REPORT WILL BE CLOSED *

**Comment by mh4x0f** [comment]
I 'll add a fix for no show this error, but this error come from another error, look the error about that.
