### ISSUE TITLE
[Request] Integrate Besside-ng

### ISSUE THREAD

**Issue by zero77** [P0cL4bs/wifipumpkin3#95]
Can you please add support for Besside-ng which is part of the Aircrack-ng suite.
https://www.aircrack-ng.org/doku.php?id=besside-ng

Ideally alongside the phishing portal as it can completely automate the hole process, of capturing handshakes and passing them to wifipumpkin3.

**Comment by mh4x0f** [comment]
no make sense, wp3 is a tool of mitm attack, not a suite for crack wifi.

**Comment by mh4x0f** [comment]
why not use the besside.ng ?
