### ISSUE TITLE
iptables: Invalid argument & unknown option (NetHunter) [No connection]

### ISSUE THREAD

**Issue by trueToastedCode** [P0cL4bs/wifipumpkin3#96]
I am able to start the access point... however unable to share internet or even load the login page when using captiveflask. I noticed the are some error's in the log:
`iptables v1.8.5 (nf_tables): Could not fetch rule set generation id: Invalid argument`
`iptables v1.8.5 (nf_tables): unknown option "--dport"`

[log.txt](https://github.com/P0cL4bs/wifipumpkin3/files/5343647/log.txt)

==================================
(Executed while nothing was running)
`root@kali:/# iptables -t nat -L`
`# Warning: iptables-legacy tables present, use iptables-legacy to see them`
`iptables v1.8.5 (nf_tables): Could not fetch rule set generation id: Invalid argument`

`root@kali:/# iptables-legacy -t nat -L`
`Chain PREROUTING (policy ACCEPT)`
`target     prot opt source               destination`
`oem_nat_pre  all  --  anywhere             anywhere`

`Chain INPUT (policy ACCEPT)`
`target     prot opt source               destination`

`Chain OUTPUT (policy ACCEPT)`
`target     prot opt source               destination`

`Chain POSTROUTING (policy ACCEPT)`
`target     prot opt source               destination`
`tetherctrl_nat_POSTROUTING  all  --  anywhere             anywhere`

`Chain oem_nat_pre (1 references)`
`target     prot opt source               destination`

`Chain tetherctrl_nat_POSTROUTING (1 references)`
`target     prot opt source               destination`

**Comment by Chotu75** [comment]
yes.. it happened with me too.. need fix
