### ISSUE TITLE
wrong iptables version 

### ISSUE THREAD

**Issue by trueToastedCode** [P0cL4bs/wifipumpkin3#97]
**Platform**
Operating System: Updated NetHunter 2020.1 onto OxygenOS 9.5.8BA (Android 9) with 4.14.18-Re4son-OOS Kernel
WiFi Adapter: TP-WN722N v3 with aircrack-ng / rtl8188eus driver (is fully working with packet injection on NetHunter and VirtualMaschine)
Wifipupmkin3: 1.0.7 - AKUANDUBA

**Description of the bug or feature request**
After i fixed the error, that some iptables commands had to be executed with iptables-legacy (log - original wifipumpkin3: https://pastebin.com/F8PMAZnz) with a script, that transforms every iptables command to iptables-legacy (script: https://pastebin.com/NiK75TnG) i am still unable to share the connection. The hotspot gets activated and i am able to connect. However i am unable to even invoke the login page when using captiveflask, where also no login notification gets triggered. It worked proviously flaweless on kali virtual maschine (log - transformed wifipumpkin3: https://pastebin.com/ntwDQRgE).

**Expected behavior**
Internet share, login notification and the invoke of the login page should work.

**To Reproduce**
A NetHunter device with compatible wifi stick is required. Wifipumpkin3 can be installed like on the Desktop Version too. My transformed version is also easy to install.... load the script into the same root folder as the original wifipumpkin3.. run the script (`python3 transform.py`). A folder called wifipumpkin3-transformed will be created (changes will be printed into the console). Install it the same way as the original version. Start wifipumkin3, set the interface and start it.

**Output `iptables -t nat -L`**
I executed it while the transformed wifipumpkin3 was running.
https://pastebin.com/QG3bvHXs

**Comment by mh4x0f** [comment]
look at documentation guide 
https://wifipumpkin3.github.io/docs/getting-started

**Comment by mh4x0f** [comment]
I' ll add a patch to include on file of configuration to change the iptables path binary. this issue can be a enhacement. wait for more details

**Comment by mh4x0f** [comment]
hi, I added a config option on config.ini  `path_binary` on session `iptables`, now you can set the version correctly of iptables.

**Comment by dr1408** [comment]
@trueToastedCode  did you get it fixed to share internet on nethunter ?
