### ISSUE TITLE
Proxy don't work - script not found in metadata

### ISSUE THREAD

**Issue by giuliaContardi** [P0cL4bs/wifipumpkin3#99]
**Description of the bug or feature request**
Proxies don't work.
I tried both pumpkinproxy (in this case script _sslstrip3_ not found) and captiveflask (in this case script _captiveflask_ not found) and no one is working. I already searched for more info and I found this closed issue: https://github.com/P0cL4bs/wifipumpkin3/issues/82
I already tried to update the system and reinstall (as said in the comment).

**To Reproduce**
For reinstallation:
```
root@kali:~# sudo apt update && sudo apt -y dist-upgrade
root@kali:~# cd wifipumpkin3
root@kali:~/wifipumpkin3# sudo python3 setup.py clean && sudo python3 setup.py install
```

For wifipumpkin3 - pumpkinproxy:
1. Open the terminal
2. `sudo wifipumpkin3`
3. `set interface wlan0`
4. `start`
5. error appear

For wifipumpkin3 - captiveflask:
1. Open the terminal
2. `sudo wifipumpkin3`
3. `set interface wlan0`
4. `set proxy captiveflask true`
5. `start`
6. error appear

**Expected behavior**
Start to working and see traffic of the devices connected to AP

**Screenshots**
_- PumpkinProxy:_
![Schermata 2020-10-20 16:22:16](https://user-images.githubusercontent.com/63663989/96599884-a8e59000-12f0-11eb-90dc-73454a758d1a.png)
_- Captiveflask:_
![Schermata 2020-10-20 16:42:56_2](https://user-images.githubusercontent.com/63663989/96602463-53f74900-12f3-11eb-882e-1dd42eda4e44.png)

**Desktop:**
* Wifipumpkin3 version: 1.0.7
* Virtual Machine: no
* Operating System: Kali Linux
* version: 2020.3

**Comment by mh4x0f** [comment]
> root@kali:~# sudo apt update && sudo apt -y dist-upgrade
root@kali:~# cd wifipumpkin3
root@kali:~/wifipumpkin3# sudo python3 setup.py clean && sudo python3 setup.py install

try to uninstall the wp3 and execute again command above.

``` sh
sudo pip3 uninstall wifipumpkin3
```

**Comment by giuliaContardi** [comment]
Now is running! Thank you so much!

**Comment by madmax117** [comment]
@giuliaContardi Hey there....I just came across the same issue as u did with captiveflask in parrot os....can u just help me out with how you got it to work finally...
